<?php
	use \Magento\Framework\Stdlib\StringUtils;
?>
<?php
	$stringFilter = new \Magento\Framework\Stdlib\StringUtils;
    $_post = $this->getPost();
    $_postUrl = $_post->getPostUrl();
    $_postName = $block->escapeHtml($_post->getTitle(), null, true);
?>
<li class="post-holder post-holder-<?php echo $_post->getId() ?>">
	<div class="post-images">
		<a href="<?php echo $_post->getPostUrl() ?>">
			<img src="<?php echo $this->getMediaFolder().$_post->getThumbnailimage() ?>"/>
		</a>
	</div>
	<div class="post-content">
		<h2 class="post-title">
			<a class="post-item-link"
			   href="<?php echo $_postUrl ?>">
				<?php echo $_postName; ?>
			</a>
		</h2> 
		<div class="time-author clearfix">
			<?php echo $this->getInfoHtml() ?>
			<?php if ($_author = $_post->getAuthor()) { ?>
			<div class="item post-author">
				<span class="label_title">
					<?php /* @escapeNotVerified */ echo __('Post by:'); ?>
				</span>
				<span class="value">
					<?php echo $block->escapeHtml($_author->getTitle()) ?>
				</span>
			</div>
		<?php } ?>
		</div>
		<div class="post-des">
			<?php echo $stringFilter->substr($_post->getShortContent(),0,335); ?>
		</div>
		<div class="post-actions clearfix">
			<div class="read-more">
				<a href="<?php echo $_post->getPostUrl() ?>"><?php /* @escapeNotVerified */ echo __('Read more'); ?><i class="fa fa-arrow-circle-right"></i></a>
			</div>
			<?php if ($block->getCommentsType()) { ?>
				<div class="block comments">
				  	<?php if ($block->getCommentsType() == 'facebook') { ?>
					<div class="fb-root"></div>
					 <script>(function(d, s, id) {
						var js, fjs = d.getElementsByTagName(s)[0];
						if (d.getElementById(id)) return;
						js = d.createElement(s); js.id = id;
						js.src = "//connect.facebook.net/<?php echo $block->getLocaleCode() ?>/sdk.js#xfbml=1&version=v2.5&appId=<?php echo $block->getFacebookAppId() ?>";
						fjs.parentNode.insertBefore(js, fjs);
					  }(document, 'script', 'facebook-jssdk'));
					</script>
					<i class="fa fa-comment"></i>
					 <span class="fb-comments-count" data-href="<?php echo $_post->getPostUrl() ?>"></span>
					 <span>Comment</span>
				  <?php } elseif ($block->getCommentsType() == 'disqus') { ?>
						<span class="disqus-comment-count" data-disqus-url="<?php echo $_post->getPostUrl() ?>">
						<script>
							var disqus_config = function () {
								this.page.url = "<?php echo $_post->getPostUrl() ?>";
								this.page.identifier = "<?php echo $_post->getPostUrl()  ?>"
							};

							(function() {
								var d = document, s = d.createElement('script');
								s.src = '//<?php echo $block->getDisqusShortname() ?>.disqus.com/embed.js';
								s.setAttribute('data-timestamp', +new Date());
								(d.head || d.body).appendChild(s);
							})();
						</script>
				 <?php } ?>
			</div>
			<?php } ?>
		</div>
	</div> 
</li>