<?php
/**
	* Copyright © 2015 Magento. All rights reserved.
	* See COPYING.txt for license details.
	*/

// @codingStandardsIgnoreFile

/* @var $block \Magento\Catalog\Block\Product\AbstractProduct */


switch ($type = $block->getType()) {
	case 'related':
		/** @var \Magento\Catalog\Block\Product\ProductList\Related $block */
		if ($exist = $block->getItems()->getSize()) {
			$type = 'related';
			$class = $type;
			$imageBlock =  $block->getLayout()->createBlock('Magento\Catalog\Block\Product\Image');
			$image = 'related_products_list';
			$title = __('Related Products');
			$items = $block->getItems();
			$limit = 0;
			$shuffle = 0;
			$showWishlist = true;
			$showCompare = true;
			$showCart = true;
			$templateType = null;
			$description = false;
		}
	break;
	case 'other':
	break;
}
?>
<?php if ($exist) { ?>
<?php if ($type == 'related' || $type == 'upsell') { ?>
<?php if ($type == 'related') { ?>
<section class="<?php echo $class; ?>" data-mage-init='{"relatedProducts":{"relatedCheckbox":".related.checkbox"}}' data-limit="<?php echo $limit; ?>" data-shuffle="<?php echo $shuffle; ?>">
<?php } else { ?>
<section class="<?php echo $class; ?>" data-mage-init='{"upsellProducts":{}}' data-limit="<?php echo $limit; ?>" data-shuffle="<?php echo $shuffle; ?>">
<?php } ?>
<?php } else { ?>
<section class="<?php echo $class; ?>">
<?php } ?>
	<div class="title-product-heading related-heading">
		<h2><?php echo $title; ?></h2>
	</div>
	<div class="relate_-content" aria-labelledby="block-<?php echo $class?>-heading">
		<div class="product-grid product-hover">
			<div id="relate_product_slider" class="owl-carousel">
				<?php $iterator = 1; ?>
				<?php 
					$i = 0;
					$rows = 1;
				?>
				<?php foreach ($items as $_item) { ?>
				<?php $available = ''; ?>
				<?php if (!$_item->isComposite() && $_item->isSaleable() && $type == 'related') { ?>
				<?php if (!$_item->getRequiredOptions()) { ?>
				<?php $available = 'related-available'; ?>
				<?php } ?>
				<?php } ?>
			<?php
				$productImage = $block->getImage($_item, $image);
			?>	
				<?php if ($i++%$rows==0) { ?>
					<div class="products-item">
				<?php } ?>
					<div class="product-item">
						<div class="item-inner">
							<?php
	                            $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
	                            $storeManager=$objectManager->create('Magento\Store\Model\StoreManagerInterface');
	                            $rootId = $storeManager->getStore()->getRootCategoryId();
	                            $categoryCollection = $_item->getCategoryCollection()->addAttributeToSelect('name')
	                                                                                       ->addAttributeToSelect('is_active')
	                                                                                       ->addAttributeToFilter('entity_id', ['neq' => $rootId])
	                                                                                       ->addUrlRewriteToResult()
	                                                                                       ->getFirstItem();                            
	                        ?>
	                        <div class="cate_name">
								<a href="<?php echo $categoryCollection->getUrl();?>" title='<?php echo $categoryCollection->getName();?>'>
									<?php echo $categoryCollection->getName();?>
								</a>
							</div>
	                        <h3 class="product-name">
								<a class="product-item-link" title="<?php echo $block->escapeHtml($_item->getName()) ?>" href="<?php echo $block->getProductUrl($_item) ?>">
									<?php echo $block->escapeHtml($_item->getName()) ?>
								</a>
							</h3>
							<div class="product-photo">
								<a href="<?php /* @escapeNotVerified */ echo $_item->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
									<?php $productImageThumb = $block->getImage($_item, 'category_page_grid-1');?>
									<span class="image0 image-switch">
										<?php echo $productImage->toHtml(); ?>
									</span>
									<span class="image1 image-switch">
										<?php echo $productImageThumb->toHtml(); ?>
									</span>
								</a>
							</div>
							<div class="product-info  clearfix">
	    						<?php /* @escapeNotVerified */ echo $block->getProductPrice($_item) ?>
	                            <?php echo $block->getReviewsSummaryHtml($_item, $templateType); ?>
	                        </div>
						</div>
					</div>
				<?php if($i%$rows==0 || $i == count($items)) { ?> 
				</div> 
				<?php } ?>
				<?php } ?>
			</div>
		</div>
    </div>
</section>
<?php } ?>
<script type="text/javascript">
	require([
		'jquery',
		'mage/mage',
		'themevast/owl'
	], function ($) {
		'use strict';

		jQuery("#relate_product_slider").owlCarousel({
			autoplay :false,
			items : 3,
			smartSpeed : 500,
			dotsSpeed : 500,
			rewindSpeed : 500,
			nav : true,
			autoplayHoverPause : true,
			dots : false,
			scrollPerPage:true,
			margin: 30,
			responsive: {
			0: {
				items: 1,
			},
			480: {
				items:2,
			},
			768: {
				items:2,
			},
			991: {
				items: 3,
			},						
			1200: {
				items: 3,
			}
		 }
		});
		$(".product-hover .owl-stage-outer").hover(function(){
	        $(this).css("padding", "10px 10px 200px").css("margin", "-10px -10px -200px");
	        }, function(){
	        $(this).css("padding", "0").css("margin", "0");
	    });
	});
</script>