<?php 
use Magento\Framework\App\Action\Action;
if($this->getConfig('enabled')){ // start enable module?>
	<?php
		$items = $block->getConfig('itemsDefault')? $block->getConfig('itemsDefault'):5;
		$speed = $block->getConfig('speed') ? $block->getConfig('speed'):1500;
		$show_navigation =$block->getConfig('next_back');
		$show_pagination = $block->getConfig('nav_ctrl');
		$auto = $block->getConfig('auto');
		$tv_column1 = $block->getConfig('tv_column1') ? $block->getConfig('tv_column1'):4;
		$tv_column2 = $block->getConfig('tv_column2') ? $block->getConfig('tv_column2'):3;
		$tv_column3 = $block->getConfig('tv_column3') ? $block->getConfig('tv_column3'):2;
		$tv_column4 = $block->getConfig('tv_column4') ? $block->getConfig('tv_column4'):1;
		$tv_column5 = $block->getConfig('tv_column5') ? $block->getConfig('tv_column5'):1;
		$_productCollection = $this->getProducts();
		$_helper = $this->helper('Magento\Catalog\Helper\Output');
	?>
	<div class="onsaleproduct">
		
		<?php			
			if ($block->getMode() == 'grid') {
				$viewMode = 'grid';
				$image = 'category_page_grid';
				$showDescription = false;
				$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
			} else {
				$viewMode = 'list';
				$image = 'category_page_list';
				$showDescription = true;
				$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
			}
			$pos = $block->getPositioned();
			
		?>
		<?php if($this->getConfig('title')){?>
			<div class="title-product-heading title-onsale-heading"><h2><?php echo $this->getConfig('title')?></h2></div>
		<?php }?>
		<?php if(!$_productCollection->getSize()): ?> 
			<div class="message info empty">	
				<p class="note-msg"><?php echo __('There are no products matching the selection.') ?></p>
			</div>
		<?php else: ?>
			<?php
			if(!$rows = $this->getConfig('items_show'))
				$rows = 1;
			?>	
			<div class="owl-carousel">
					<?php $_collectionSize = $_productCollection->count() ?>
					<?php $i=0; foreach ($_productCollection as $_product): ?>
						<?php if($i %$rows == 0) echo "<div class='item newproductslider-item clearfix'>"; ?>

							<div class="product-item">
								<?php
								$productImage = $block->getImage($_product, $image);
								if ($pos != null) {
									$position = ' style="left:' . $productImage->getWidth() . 'px;'
										. 'top:' . $productImage->getHeight() . 'px;"';
								}
								?>
								<?php // Product Image ?>
								<div class="product-photo">
									<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
										<?php $productImageThumb = $block->getImage($_product, 'category_page_grid-1');?>
										<span class="image0 image-switch">
											<?php echo $productImage->toHtml(); ?>
										</span>
										<span class="image1 image-switch">
											<?php echo $productImageThumb->toHtml(); ?>
										</span>
									</a>
									<div class="quickview-product">
		                                <a  data-role="quickview-button" data-id="<?php echo $_product->getId(); ?>" href="<?php echo $block->getUrl('quickview/product/quickview/id/' . $_product->getId()) ?>" title="" class="ajax diamond tooltip-toggle" data-placement="top" data-original-title="<?php echo ('Quick 5') ?>">
		                                <?php echo $block->escapeHtml(__('Quick 5')); ?>
		                                </a>
		                            </div>
								</div>
								<div class="product-info">
									<?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
										<?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
										<h3 class="product-name">
											<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
												<?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
											</a>
										</h3>
										<?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
										<div class="actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
										<?php if ($_product->isSaleable()): ?>
											<?php $postParams = $block->getAddToCartPostParams($_product); ?>
											<form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
												<input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
												<input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
												<?php echo $block->getBlockHtml('formkey')?>
												<button class="btn btn-add-to-cart" type="submit"
											title="<?php echo $block->escapeHtml(__('test3')); ?>" >
										<i class="storm-shopping-bag"></i><?php echo $block->escapeHtml(__('test3')); ?>
									</button>
											</form>
										<?php else: ?>
											<?php if ($_product->getIsSalable()): ?>
												<button class="btn btn-add-to-cart"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></button>
											<?php else: ?>
												<button class="btn btn-add-to-cart"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></button>
											<?php endif; ?>
										<?php endif; ?>
									</div>
								</div>
							<?php $i++;?>
						</div>
						<?php if($i %$rows == 0) echo "</div>"; ?>                  
					<?php endforeach; ?>
						<?php if($i %$rows != 0) echo "</div>"; ?>                
				</div>
		<?php if (!$block->isRedirectToCartEnabled()) : ?>
			<script type="text/x-magento-init">
			{
				"[data-role=tocart-form], .form.map.checkout": {
					"catalogAddToCart": {}
				}
			}
			</script>
		<?php endif; ?>
			<script>
				require([
					'jquery',
					'mage/mage',
					'themevast/owl'
				], function ($) {
					'use strict';

					jQuery(".onsaleproduct .owl-carousel").owlCarousel({
						autoplay :<?php echo $auto==1 ? 'true':'false' ?>,
						items : 1,
						smartSpeed : <?php echo $speed ?>,
						dotsSpeed : <?php echo $speed ?>,
						rewindSpeed : <?php echo $speed ?>,
						nav : true,
						autoplayHoverPause : true,
						dots :<?php echo $show_pagination==1 ? 'true':'false' ;  ?>,
						scrollPerPage:true,
						margin: 30,
						responsive: {
						0: {
							items: 1,
						},
						480: {
							items: 1,
						},
						768: {
							items: 1,
						},
						991: {
							items: 1,
						},						
						1200: {
							items: 1,
						}
					 }
					});
				});
			</script>
	<?php endif; ?>
	</div>
<?php } ?>