<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Form\Login\Info $block */
?>
<?php if ($block->getRegistration()->isAllowed()): ?>
<div class="pl-md-5 col-12 col-md-6 mt-5 mt-md-0">
    <h3 class="block-title">
        <strong id="block-new-customer-heading" role="heading" aria-level="2"><?= $block->escapeHtml(__('New Customers')) ?></strong>
</h3>
    <div class="block-content" aria-labelledby="block-new-customer-heading">
        <p class="mt-2 mb-3"><?= $block->escapeHtml(__('Creating an account has many benefits: check out faster, keep more than one address, track orders and more.')) ?></p>
        <div class="actions-toolbar">
            <a href="<?= $block->escapeUrl($block->getCreateAccountUrl()) ?>" class="btn btn-dark text-white"><span><?= $block->escapeHtml(__('Create an Account')) ?></span></a>
        </div>
    </div>
</div>
<?php endif; ?>
