<?php 
use Magento\Framework\App\Action\Action;

if($this->getConfigSys('enabled')) { ?>
	<?php 
	$_productCollection = $this->getProductCollection();
	$_helper = $this->helper('Magento\Catalog\Helper\Output');
	$random_string = $this->generateRandomString(10);
	$idDeal = 'dealslider_'.$this->getConfig('identify','tv');
	$productfirst=$_productCollection->getFirstItem();
	$show_time=true;
	?>
	<div id="<?php echo $idDeal?>">
		<div class="hotdeal deal-preload">	
			<?php			
				if ($block->getMode() == 'grid') {
					$viewMode = 'grid';
					$image = 'category_page_grid';
					$showDescription = false;
					$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
				} else {
					$viewMode = 'list';
					$image = 'category_page_list';
					$showDescription = true;
					$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
				}
				$pos = $block->getPositioned();				
			?>
			<?php if(!$_productCollection->getSize()) { ?> 
				<div class="message info empty">	
					<p class="note-msg">
						<?php echo __('There are no products matching the selection.') ?>
					</p>
				</div>
			<?php } else { ?>
				<?php
				if(!$rows = $this->getConfigSys('row_show'))
					$rows = 1;
				?>	
				<div class="deals-product">
					<?php if($this->getConfig('title',$this->getConfigSys('title'))) { ?>
						<div class="title-deals clearfix title-product-heading">
							<h2>
								<?php echo $this->getConfig('title',$this->getConfigSys('title')) ?>
							</h2>
						</div>
					<?php }?>
					<div class="owl owl-deals">
						<div class="dealFirst_loading"></div>
						<?php $_collectionSize = $_productCollection->count() ?>
						<?php $i=0; foreach ($_productCollection as $_product) { ?>
							<?php if($i %$rows == 0) echo "<div class='item deal_item'>"; ?>
								<div class="product-item">
									<div class="item-inner">
										<div class="hot-dealss">
											<span>
												<?php echo __('Hot Deals') ?>
											</span>											
										</div>
										<div class="new-sale-label">
											<?php
											$specialprice = $_product->getSpecialPrice();
											$specialPriceFromDate = $_product->getSpecialFromDate();
											$specialPriceToDate = $_product->getSpecialToDate();
											$_price=$_product->getPrice();
											$_finalPrice=$_product->getFinalPrice();
											$today = time();
											?>
											<?php 
											if ($specialprice) {
												if ($today >= strtotime($specialPriceFromDate) && $today <= strtotime($specialPriceToDate) || $today >= strtotime($specialPriceFromDate) && is_null($specialPriceToDate)) { ?>
													<span class="label-product label-sale">
														<?php if($_finalPrice < $_price) { ?>
															<?php $_savePercent = 100 - round(($_finalPrice / $_price)*100); ?>
															<?php echo __('-%1',$_savePercent."%");?>
														<?php } ?>
													</span>
												<?php }
											}
											?>
											<?php
											$now = date("Y-m-d");
											$newsFrom = substr($_product->getNewsFromDate(), 0, 10);
											$newsTo = substr($_product->getNewsToDate(), 0, 10);

											if (($newsTo != '' || $newsFrom != '')) {
												if (($newsTo != '' && $newsFrom != '' && $now >= $newsFrom && $now <= $newsTo) || ($newsTo == '' && $now >= $newsFrom) || ($newsFrom == '' && $now <= $newsTo)) {?>
													<span class="label-product label-new">
														<?php echo __('New'); ?>
													</span>
												<?php }
											} ?>
										</div>
									<?php
									$productImage = $block->getImage($_product, $image);
									if ($pos != null) {
										$position = ' style="left:' . $productImage->getWidth() . 'px;'
											. 'top:' . $productImage->getHeight() . 'px;"';
									}
									?>
									<?php // Product Image ?>
									<div class="product-photo">
										<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
											<?php $productImageThumb = $block->getImage($_product, 'category_page_grid-1');?>
											<span class="image0 image-switch">
												<?php echo $productImage->toHtml(); ?>
											</span>
											<span class="image1 image-switch">
												<?php echo $productImageThumb->toHtml(); ?>
											</span>
										</a>
									</div>
									<div class="product-info">
										<?php // Timer  ?>
								<?php if( isset($productfirst) && $productfirst->getFinalPrice() < $productfirst->getPrice() && $show_time && $productfirst->getSpecialToDate()!=''){
									$date = date('G:i:s', strtotime($productfirst->getSpecialToDate()));
									if ($date == "0:00:00") {
										$targetDate = date('m/d/Y \2\3\:\5\9\:\0\0', strtotime($productfirst->getSpecialToDate()));
									} else {
										$targetDate = date('m/d/Y G:i:s', strtotime($productfirst->getSpecialToDate()));
									}
									?>
									<div class="deal-timmer">										
										<div id="deal-<?php echo $random_string ?>" class="item deal-time"></div>
										<script type="text/javascript">
											require(['jquery','themevast/datetime'],function () {
												jQuery("#deal-<?php echo $random_string ?>").CustomDate({
													targetDate:"<?php echo $targetDate; ?>",
													displayFormat:"<span class='countdown-section'><span class='countdown-amount'>%%D%%</span><span class='countdown-period'><?php echo __('Days') ?></span></span><span class='countdown-section'><span class='countdown-amount'>%%H%%</span><span class='countdown-period'><?php echo __('Hrs') ?></span></span><span class='countdown-section'><span class='countdown-amount'>%%M%%</span><span class='countdown-period'><?php echo __('Mins') ?></span></span><span class='countdown-section'><span class='countdown-amount'>%%S%%</span><span class='countdown-period'><?php echo __('Secs') ?></span></span>",
												});
											});
										</script>
									</div>
								<?php } ?>
										<?php if($this->getConfigSys('review')) { ?>
											<?php echo $block->getReviewsSummaryHtml($_product, $templateType,true); ?>
										<?php } ?>
										<?php
											$_productNameStripped = $block->stripTags($_product->getName(), null, true);
										?>
										<p class="product-name">
											<a href="<?php echo $_product->getProductUrl() ?>">
												<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
											</a>
										</p>										
										<?php if($this->getConfigSys('show_price')) { ?>
											<?php echo $block->getProductPrice($_product) ?>
										<?php } ?>
										<?php if($this->getConfigSys('addtowishlist') || $this->getConfigSys('addtocompare') || $this->getConfigSys('addtocart')) { ?>
											<div class="actions">
												<ul class="add-to-links">
												<?php if( $this->getConfigSys('addtocompare')) { ?>
													<?php
													$compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
													?>
													<li>
														<a href="#"
															class="action compare tooltip-toggle"
															title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
															aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
															data-post='<?php  echo $compareHelper->getPostDataParams($_product); ?>'
															role="button">
															<i class="fa fa-expand" aria-hidden="true"></i>
															<span class="tooltip-content">
																<?php echo $block->escapeHtml(__('Add Compare')); ?>
															</span>
														</a>
													</li>
												<?php } ?>
											<?php if($this->getConfigSys('addtowishlist')) { ?>
												<?php if($this->helper('Magento\Wishlist\Helper\Data')->isAllow()) { ?>
												<li>
													<a href="#"
														class="action wishlist tooltip-toggle" data-toggle="tooltip"
														title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
														aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
														data-post='<?php  echo $block->getAddToWishlistParams($_product); ?>'
														data-action="add-to-wishlist"
														role="button">
														<i class="fa fa-heart" aria-hidden="true"></i>
														<span class="tooltip-content">
															<?php echo $block->escapeHtml(__('Add Wishlist')); ?>
														</span>
													</a>
												</li>
												<?php } ?>
											<?php } ?>											
												<li>
													<div class="actions-primary">
														<?php if ($_product->isSaleable()) { ?>
															<?php $postParams = $block->getAddToCartPostParams($_product); ?>
															<form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $block->getAddToCartUrl($_product); ?>" method="post">
																<input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
																<input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
																<?php echo $block->getBlockHtml('formkey')?>
																<button class="btn btn-add-to-cart tooltip-toggle" type="submit" data-toggle="tooltip" title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>" >
																	<i class="fa fa-shopping-basket" aria-hidden="true"></i>
																	<span class="tooltip-content">
																		<?php echo $block->escapeHtml(__('Add to Cart')); ?>
																	</span>
																</button>
															</form>
														<?php } else { ?>
															<?php if ($_product->getIsSalable()) { ?>
																<button class="btn btn-add-to-cart tooltip-toggle">
																	<i class="fa fa-shopping-basket" aria-hidden="true"></i>
																	<span class="tooltip-content">
																		<?php echo $block->escapeHtml(__('Add to Cart')); ?>
																	</span>
																</button>
															<?php } else { ?>
																<button class="btn btn-add-to-cart tooltip-toggle">
																	<i class="fa fa-shopping-basket" aria-hidden="true"></i>
																	<span class="tooltip-content">
																		<?php echo $block->escapeHtml(__('Add to Cart')); ?>
																	</span>
																</button>
															<?php } ?>
														<?php } ?>
													</div>
												</li>
											</ul>
										</div>
										<?php } ?>	
									</div>
								<?php $i++; ?>
								</div>
							</div>
							<?php if($i %$rows == 0) echo "</div>"; ?>                  
						<?php }; ?>
							<?php if($i %$rows != 0) echo "</div>"; ?>                
					</div>
				</div>
			<?php if (!$block->isRedirectToCartEnabled()) { ?>
				<script type="text/x-magento-init">
				{
					"[data-role=tocart-form], .form.map.checkout": {
						"catalogAddToCart": {}
					}
				}
				</script>
			<?php } ?>
				<script>
					require([
						'jquery',
						'mage/mage',
						'themevast/owl'
					], function ($) {
						'use strict';
					jQuery(document).ready(function ($) {
						(function (element) {
								var $element = $(element);
								setTimeout(function () {
										jQuery(".hotdeal").removeClass('deal-preload');
										jQuery('.dealFirst_loading').remove();
										hotDealSlider($element);

								}, 500);
							function hotDealSlider($element){
								var hotDeal = $(".hotdeal .owl",$element);
								hotDeal.owlCarousel({
										autoPlay : <?php if($this->getConfigSys('auto')) echo 'true'; else echo 'false'; ?>,
										items : <?php if($this->getConfigSys('itemsDefault')) echo $this->getConfigSys('itemsDefault'); else echo '1'; ?>,
										itemsDesktop : [1199,1],
										itemsDesktopSmall : [980,<?php echo $this->getConfigSys('itemsDesktopSmall'); ?>],
										itemsTablet: [768,<?php echo $this->getConfigSys('itemsTablet'); ?>],
										itemsMobile : [479,<?php echo $this->getConfigSys('itemsMobile'); ?>],
										slideSpeed : <?php if($this->getConfigSys('speed')) echo $this->getConfigSys('speed'); else echo '500'; ?>,
										navigation : <?php if($this->getConfigSys('next_back')) echo 'true'; else echo 'false'; ?>,
										stopOnHover : true,
										pagination :<?php if($this->getConfigSys('nav_ctrl')) echo 'true'; else echo 'false'; ?>,
										/* scrollPerPage:true, */
									});
							}
						})('#<?php echo $idDeal ?>');
					});
				});
				</script>
		<?php } ?>
		</div>
	</div>
<?php } ?>