<?php 
use Magento\Framework\App\Action\Action;

if($this->getConfig('enabled')) { ?>
	<?php
	$items = $block->getConfig('itemsDefault')? $block->getConfig('itemsDefault'):5;
	$speed = $block->getConfig('speed') ? $block->getConfig('speed'):1500;
	$show_navigation =$block->getConfig('next_back');
	$navigation=false;
	if($show_navigation==1){
		$navigation=true;
	}
	$show_pagination = $block->getConfig('nav_ctrl');
	$auto = $block->getConfig('auto');
	$tvHelper = $this->helper('Themevast\Themevast\Helper\Data');
	$show_shortdescription = $block->getConfig('description')==1 ? true:false;
	$length = $block->getConfig('maxlength') ? $block->getConfig('maxlength'):50;
	$_productCollection = $this->getProducts();
	$_helper = $this->helper('Magento\Catalog\Helper\Output');
	?>
	<div class="featuredproducts product-hover">
		<?php			
			if ($block->getMode() == 'grid') {
				$viewMode = 'grid';
				$image = 'category_page_grid';
				$showDescription = false;
				$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
			} else {
				$viewMode = 'list';
				$image = 'category_page_list';
				$showDescription = true;
				$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
			}
			$pos = $block->getPositioned();			
		?>
		<?php if($this->getConfig('title')) { ?>
			<div class="title-product-heading title-featured-heading">
				<h2>
					<?php echo $this->getConfig('title')?>					
					<span class="b-title_separator"><span>
					</span></span>
				</h2>
			</div>
		<?php }?>
		<?php if(!$_productCollection->getSize()) { ?> 
			<div class="message info empty">	
				<p class="note-msg">
					<?php echo __('There are no products matching the selection.') ?>
				</p>
			</div>
		<?php } else { ?>
			<?php
			if(!$rows = $this->getConfig('items_show'))
				$rows = 2;
			?>	
				<div class="owl-carousel">
					<?php $_collectionSize = $_productCollection->count() ?>
					<?php $i=0; foreach ($_productCollection as $_product) { ?>
						<?php if($i %$rows == 0) echo "<div class='item newproductslider-item clearfix'>"; ?>
							<div class="product-item">
								<div class="item-inner">
									<?php
									$productImage = $block->getImage($_product, $image);
									if ($pos != null) {
										$position = ' style="left:' . $productImage->getWidth() . 'px;'
											. 'top:' . $productImage->getHeight() . 'px;"';
									}
								?>
								<?php // Product Image ?>
								<div class="product-photo">
									<div class="new-sale-label">
								        <?php
										$specialprice = $_product->getSpecialPrice();
										$specialPriceFromDate = $_product->getSpecialFromDate();
										$specialPriceToDate = $_product->getSpecialToDate();
										$_price=$_product->getPrice();
										$_finalPrice=$_product->getFinalPrice();
										$today = time();
										?>								
										<?php 
										if ($specialprice) {
											if ($today >= strtotime($specialPriceFromDate) && $today <= strtotime($specialPriceToDate) || $today >= strtotime($specialPriceFromDate) && is_null($specialPriceToDate)) { ?>
												<span class="label-product label-sale">
													<?php if($_finalPrice < $_price) { ?>
														<?php $_savePercent = 100 - round(($_finalPrice / $_price)*100); ?>
														<?php echo __('-%1',$_savePercent."%");?>
													<?php } ?>
												</span>
											<?php }
										}
										?>
										<?php
										$now = date("Y-m-d");
										$newsFrom = substr($_product->getNewsFromDate(), 0, 10);
										$newsTo = substr($_product->getNewsToDate(), 0, 10);

										if (($newsTo != '' || $newsFrom != '') && !$specialprice) {
											if (($newsTo != '' && $newsFrom != '' && $now >= $newsFrom && $now <= $newsTo) || ($newsTo == '' && $now >= $newsFrom) || ($newsFrom == '' && $now <= $newsTo)) {?>
												<span class="label-product label-new">
													<?php echo __('New'); ?>
												</span>
											<?php }
										} ?>
								       </div>
									<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
										<?php $productImageThumb = $block->getImage($_product, 'category_page_grid-1');?>
										<span class="image0 image-switch">
											<?php echo $productImage->toHtml(); ?>
										</span>
										<span class="image1 image-switch">
											<?php echo $productImageThumb->toHtml(); ?>
										</span>
									</a>
									<ul class="add-to-links clearfix">
										<?php if( $this->getConfig('addtowishlist')) { ?>
											<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()) { ?>
											<li class="wishlist">
												<a href="#"
												   title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
												   aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
												   data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>'
												   data-action="add-to-wishlist"
												   role="button">
													<span class="tolltip"><?php echo $block->escapeHtml(__('Add to Wishlist')); ?></span>
													<i class="icon-heart icon"></i>
												</a>
											</li>
											<?php } ?>
										<?php } ?>
										<?php if( $this->getConfig('addtocompare')) { ?>
											<?php
											$compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
											?>
											<li class="compare">
												<a href="#"	title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
													aria-label="<?php echo $block->escapeHtml(__('Compare')); ?>"
													data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>'
													role="button">
													<span class="tolltip">
														<?php echo $block->escapeHtml(__('Compare')); ?>
													</span>
													<i class="icon-refresh icons"></i>
												</a>
											</li>
										<?php } ?>
										<li class="quickview-product">
			                                <a data-role="quickview-button" data-id="<?php echo $_product->getId(); ?>" href="<?php echo $block->getUrl('quickview/product/quickview/id/' . $_product->getId()) ?>" title="" class="ajax diamond tooltip-toggle" data-placement="top" data-original-title="<?php echo ('Quick 4') ?>">
												<span class="tolltip">
													<?php echo $block->escapeHtml(__('Quick 4')); ?>
												</span>
												<i class="icon-magnifier-add icons"></i>
			                                </a>
			                            </li>
									</ul>
								</div>
								<div class="product-info clearfix">
									<?php
										$_productNameStripped = $block->stripTags($_product->getName(), null, true);
									?>
									<h3 class="product-name">
										<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
											<?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
										</a>
									</h3>									
									<?php if($this->getConfig('show_price')) { ?>
										 <?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
									<?php } ?>
									<?php if($this->getConfig('addtowishlist') || $this->getConfig('addtocompare') || $this->getConfig('addtocart')) { ?>
										<div class="actions clearfix">										
											<?php if ($this->getConfig('addtocart')) { ?>
												<div class="actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
													<?php if ($_product->isSaleable()) { ?>
														<?php $postParams = $block->getAddToCartPostParams($_product); ?>
														<form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
															<input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
															<input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
															<?php echo $block->getBlockHtml('formkey')?>
															<button class="btn btn-add-to-cart" type="submit" title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>" >
																<span>
																	<?php echo $block->escapeHtml(__('Add to Cart')); ?>
																</span>
															</button>
														</form>
													<?php } else { ?>
														<?php if ($_product->getIsSalable()) { ?>
															<button class="btn btn-add-to-cart">
																<span>
																	<?php /* @escapeNotVerified */ echo __('In stock') ?>
																</span>
															</button>
														<?php } else { ?>
															<button class="btn btn-add-to-cart">
																<span>
																	<?php /* @escapeNotVerified */ echo __('Out of stock') ?>
																</span>
															</button>
														<?php } ?>
													<?php } ?>
												</div>
											<?php } ?>
										</div>
									<?php } ?>								
								</div>								
								</div>
							<?php $i++;?>
						</div>
						<?php if($i %$rows == 0) echo "</div>"; ?>                  
						<?php } ?>
						<?php if($i %$rows != 0) echo "</div>"; ?>                
				</div>
		<?php if (!$block->isRedirectToCartEnabled()) { ?>
			<script type="text/x-magento-init">
			{
				"[data-role=tocart-form], .form.map.checkout": {
					"catalogAddToCart": {}
				}
			}
			</script>
		<?php } ?>
		<script type="text/javascript">
				require([
					'jquery',
					'mage/mage',
					'themevast/owl'
				], function ($) {
					'use strict';

					jQuery(".featuredproducts .owl-carousel").owlCarousel({
						autoplay :false,
						items : 4,
						smartSpeed : 500,
						dotsSpeed : 500,
						rewindSpeed : 500,
						nav : true,
						autoplayHoverPause : true,
						dots : false,
						scrollPerPage:true,
						margin: 30,
						responsive: {
						0: {
							items: 1,
						},
						480: {
							items:2,
						},
						768: {
							items:3,
						},
						991: {
							items:2,
						},						
						1200: {
							items:2,
						}
					 }
					});
					$(".product-hover .owl-stage-outer").hover(function(){
				        $(this).css("padding", "10px 10px 200px").css("margin", "-10px -10px -200px");
				        }, function(){
				        $(this).css("padding", "0").css("margin", "0");
				    });
				});
			</script>
	<?php } ?>
	</div>
<?php } ?>