<?php 
use Magento\Framework\App\Action\Action;
if($this->getConfig('enabled')){ // start enable module?>
	<?php 
		$items = $block->getConfig('itemsDefault')? $block->getConfig('itemsDefault'):5;
		$speed = $block->getConfig('speed') ? $block->getConfig('speed'):1500;
		$show_navigation =$block->getConfig('next_back');
		$navigation=false;
		if($show_navigation==1){
			$navigation=true;
		}
		$show_pagination = $block->getConfig('nav_ctrl');
		$auto = $block->getConfig('auto');
		$_productCollection = $this->getProducts();
        $_helper = $this->helper('Magento\Catalog\Helper\Output');
		$tvHelper = $this->helper('Themevast\Themevast\Helper\Data');
		$show_shortdescription = $block->getConfig('description')==1 ? true:false;
		$length = $block->getConfig('maxlength') ? $block->getConfig('maxlength'):50;
	?>
	<div class="newproduct">
		<?php			
			if ($block->getMode() == 'grid') {
				$viewMode = 'grid';
				$image = 'category_page_grid';
				$showDescription = false;
				$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
			} else {
				$viewMode = 'list';
				$image = 'category_page_list';
				$showDescription = true;
				$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
			}
			$pos = $block->getPositioned();
			
		?>
		<?php if($this->getConfig('title')){?>
			<div class="title-product-heading title-new-heading">
				<h2><?php echo $this->getConfig('title')?></h2>
			</div>
		<?php }?>
		<?php if(!$_productCollection->getSize()): ?> 
			<div class="message info empty">	
				<p class="note-msg"><?php echo __('There are no products matching the selection.') ?></p>
			</div>
		<?php else: ?>
			<?php
				$rows = $this->getConfig('row_show');
			?>	
				<div class="owl-carousel">
					<?php $_collectionSize = $_productCollection->count() ?>
					<?php $i=0; foreach ($_productCollection as $_product): ?>
						<?php if($i %$rows == 0) echo "<div class='item product-list-item newproductslider-item clearfix'>"; ?>

							<div class="item-inner">
								<?php
								$productImage = $block->getImage($_product, $image);
								if ($pos != null) {
									$position = ' style="left:' . $productImage->getWidth() . 'px;'
										. 'top:' . $productImage->getHeight() . 'px;"';
								}
								?>
								<?php // Product Image ?>
								<div class="product-photo">
									<div class="new-sale-label">
										<?php
										$specialprice = $_product->getSpecialPrice();
										$specialPriceFromDate = $_product->getSpecialFromDate();
										$specialPriceToDate = $_product->getSpecialToDate();

										$today = time();
										if ($specialprice) {
											if ($today >= strtotime($specialPriceFromDate) && $today <= strtotime($specialPriceToDate) || $today >= strtotime($specialPriceFromDate) && is_null($specialPriceToDate)) { ?>
												<span class="label-product label-sale"><?php echo __('Sale'); ?></span>
											<?php }
										}
										?>
										<?php
										$now = date("Y-m-d");
										$newsFrom = substr($_product->getNewsFromDate(), 0, 10);
										$newsTo = substr($_product->getNewsToDate(), 0, 10);

										if ($newsTo != '' || $newsFrom != '') {
										if (($newsTo != '' && $newsFrom != '' && $now >= $newsFrom && $now <= $newsTo) || ($newsTo == '' && $now >= $newsFrom) || ($newsFrom == '' && $now <= $newsTo)) {?>
												<span class="label-product label-new"><?php echo __('New'); ?></span>
										<?php }
										} ?>
									</div>
									<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
										<?php $productImageThumb = $block->getImage($_product, 'category_page_grid-1');?>
										<span class="image0 image-switch">
											<?php echo $productImage->toHtml(); ?>
										</span>
										<span class="image1 image-switch">
											<?php echo $productImageThumb->toHtml(); ?>
										</span>
									</a>
									<div class="quickview-product">
		                                <a  data-role="quickview-button" data-id="<?php echo $_product->getId(); ?>" href="<?php echo $block->getUrl('quickview/product/quickview/id/' . $_product->getId()) ?>" title="" class="ajax diamond tooltip-toggle" data-placement="top" data-original-title="<?php echo ('Quick view') ?>"><i class="storm-eye"></i>
		                                <?php echo $block->escapeHtml(__('Quick View')); ?>
		                                </a>
		                            </div>
								</div>
								<div class="product-info  clearfix">
									<?php
										$_productNameStripped = $block->stripTags($_product->getName(), null, true);
									?>
									<h3 class="product-name">
										<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
											<?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
										</a>
									</h3>
									
										
									<?php if( $this->getConfig('show_price') ): ?>
										 <?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
									<?php endif; ?>
									<?php if($this->getConfig('review')): ?>
										<?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
									<?php endif; ?>
									<div class="actions clearfix">
									
										<?php if ($this->getConfig('addtocart')) { ?>
										<div class="actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
											<?php if ($_product->isSaleable()): ?>
												<?php $postParams = $block->getAddToCartPostParams($_product); ?>
												<form data-role="tocart-form" action="<?php  echo $postParams['action']; ?>" method="post">
													<input type="hidden" name="product" value="<?php  echo $postParams['data']['product']; ?>">
													<input type="hidden" name="<?php echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php  echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
													<?php echo $block->getBlockHtml('formkey')?>
													<button type="submit"
															title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
															class="btn btn-add-to-cart">
														<span><i class="storm-shopping-bag"></i><?php  echo __('Add to Cart') ?></span>
													</button>
												</form>
											<?php else: ?>
												<?php if ($_product->getIsSalable()): ?>
													<div class="stock available"><span><?php  echo __('In stock') ?></span></div>
												<?php else: ?>
													<div class="stock unavailable"><span><?php  echo __('Out of stock') ?></span></div>
												<?php endif; ?>
											<?php endif; ?>
										</div>
										<?php }?>	
										
										<?php if( $this->getConfig('addtowishlist') || $this->getConfig('addtocompare') ){?>
											<ul class="add-to-links clearfix">
											<?php if( $this->getConfig('addtowishlist')): ?>
													<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
													<li class="wishlist">
														<a href="#"
														   class="action towishlist"
														   title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
														   aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
														   data-post='<?php  echo $block->getAddToWishlistParams($_product); ?>'
														   data-action="add-to-wishlist"
														   role="button">
															<i class="storm-heart"></i>
														</a>
													</li>
													<?php endif; ?>
												<?php endif; ?>
						
											<?php if( $this->getConfig('addtocompare')): ?>
											<?php
												$compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
												?>
												<li class="compare"><a href="#"
												   class="action tocompare"
												   title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
												   aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
												   data-post='<?php  echo $compareHelper->getPostDataParams($_product); ?>'
												   role="button">
													<i class="storm-balance"></i>
													</a>
												</li>
											<?php endif; ?>
											</ul>
										<?php }?>
									
								</div>
								</div>
							<?php $i++;?>
						</div>
						<?php if($i %$rows == 0) echo "</div>"; ?>                  
					<?php endforeach; ?>
						<?php if($i %$rows != 0) echo "</div>"; ?>                
				</div>
		<?php if (!$block->isRedirectToCartEnabled()) : ?>
			<script type="text/x-magento-init">
			{
				"[data-role=tocart-form], .form.map.checkout": {
					"catalogAddToCart": {}
				}
			}
			</script>
		<?php endif; ?>
		<script type="text/javascript">
				require([
					'jquery',
					'mage/mage',
					'themevast/owl'
				], function ($) {
					'use strict';

					jQuery(".newproduct .owl-carousel").owlCarousel({
						autoplay :false,
						items : 12,
						smartSpeed : 500,
						dotsSpeed : 500,
						rewindSpeed : 500,
						nav : true,
						autoplayHoverPause : true,
						dots : false,
						scrollPerPage:true,
						margin: 30,
						responsive: {
						0: {
							items: 1,
						},
						480: {
							items:2,
						},
						768: {
							items:2,
						},
						991: {
							items:3,
						},						
						1200: {
							items:4,
						}
					 }
					});
				});
			</script>
	<?php endif; ?>
	</div>
<?php } ?>