<?php 
use Magento\Framework\App\Action\Action;
$_productCollection = $this->getData('productCollection');
$rows = $block->getConfig('row');
$_collectionSize = $_productCollection->count();
$_imgHelper = $this->helper('Themevast\Categorytab\Helper\Image');
$imageBlock =  $block->getLayout()->createBlock('Magento\Catalog\Block\Product\Image');
$image = 'new_products_content_widget_grid';
$type = 'widget-new-grid';
$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
$showWishlist = $block->getConfig('wishlist');
$showCompare = $block->getConfig('compare');
$showCart = $block->getConfig('addtocart');
?>

<?php if($_collectionSize<1){?>
	<div class="message info empty">	
		<p class="note-msg"><?php echo __('There are no products matching the selection.') ?></p>
	</div>
<?php }?>
<div class="owl-carousel">
		<?php $i=0; foreach($_productCollection as $_item): 
		$productImage = $block->getImage($_item, $image);
		$i++;?>
			<?php if($i % $rows == 1 || $rows == 1):?>
				<div class="product-item item">
			<?php endif;?>
				<div class="item-inner">
					
                    <?php // Product Image ?>
					<div class="product-photo">
						<div class="new-sale-label">
					        <?php
					         $specialprice = $_item->getSpecialPrice();
					         $specialPriceFromDate = $_item->getSpecialFromDate();
					         $specialPriceToDate = $_item->getSpecialToDate();
					         $_price=$_item->getPrice();
					         $_finalPrice=$_item->getFinalPrice();
					         $today = time();?>
					
					         <?php 
					         if ($specialprice) {
					          if ($today >= strtotime($specialPriceFromDate) && $today <= strtotime($specialPriceToDate) || $today >= strtotime($specialPriceFromDate) && is_null($specialPriceToDate)) { ?>
					           <span class="label-product label-sale">
					           		<?php if($_finalPrice < $_price): ?>
							          <?php $_savePercent = 100 - round(($_finalPrice / $_price)*100); ?>
							            <?php echo __('-%1',$_savePercent."%");?>
							          <?php endif; ?>
					           </span>
					          <?php }
					         }
					         ?>
					         <?php
					         $now = date("Y-m-d");
					         $newsFrom = substr($_item->getNewsFromDate(), 0, 10);
					         $newsTo = substr($_item->getNewsToDate(), 0, 10);

					         if (($newsTo != '' || $newsFrom != '') && !$specialprice) {
					         if (($newsTo != '' && $newsFrom != '' && $now >= $newsFrom && $now <= $newsTo) || ($newsTo == '' && $now >= $newsFrom) || ($newsFrom == '' && $now <= $newsTo)) {?>
					           <span class="label-product label-new"><?php echo __('New'); ?></span>
					         <?php }
					         } ?>
					       </div>
						<a href="<?php /* @escapeNotVerified */ echo $_item->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
							<?php $productImageThumb = $block->getImage($_item, 'category_page_grid-1');?>
							<span class="image0 image-switch">
								<?php echo $productImage->toHtml(); ?>
							</span>
							<span class="image1 image-switch">
								<?php echo $productImageThumb->toHtml(); ?>
							</span>
						</a>
						<div class="quickview-product">
                            <a  data-role="quickview-button" data-id="<?php echo $_item->getId(); ?>" href="<?php echo $block->getUrl('quickview/product/quickview/id/' . $_item->getId()) ?>" title="" class="ajax diamond tooltip-toggle" data-placement="top" data-original-title="<?php echo ('Quick 7') ?>">
                            <?php echo $block->escapeHtml(__('Quick 7')); ?>
                            </a>
                        </div>
					</div>
					<div class="product-info clearfix">
						<?php
						$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
						$storeManager=$objectManager->create('Magento\Store\Model\StoreManagerInterface');
						$rootId = $storeManager->getStore()->getRootCategoryId();
						$categoryCollection = $_item->getCategoryCollection()->addAttributeToSelect('name')
																				   ->addAttributeToSelect('is_active')
																				   ->addAttributeToFilter('entity_id', ['neq' => $rootId])
																				   ->addUrlRewriteToResult()
																				   ->getFirstItem();                            
						?>
						<div class="cate_name"><a href="<?php echo $categoryCollection->getUrl();?>" title='<?php echo $categoryCollection->getName();?>'><?php echo $categoryCollection->getName();?></a></div>
					<h3 class="product-name">
						<a title="<?php echo $block->escapeHtml($_item->getName()) ?>"
						   href="<?php echo $block->getProductUrl($_item) ?>"
						   class="product-item-link">
							<?php echo $block->escapeHtml($_item->getName()) ?>
						</a>
					</h3>
						<?php echo $block->getProductPrice($_item); ?>
						<?php //if ($templateType): ?>
								<?php //echo $block->getReviewsSummaryHtml($_item, $templateType,true); ?>
							<?php //endif; ?>
					</div>
					
					<div class="actions clearfix">
						<?php if ($showCart): ?>
							<div class="actions-primary">
								<?php if ($_item->isSaleable()): ?>
									<?php $postParams = $block->getAddToCartPostParams($_item); ?>
									<form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $block->getAddToCartUrl($_item); ?>" method="post">
										<input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
										<input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
										<?php echo $block->getBlockHtml('formkey')?>
										<button class="btn btn-add-to-cart" type="submit"
												title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>" >
											<span><?php echo $block->escapeHtml(__('Add to Cart')); ?></span>
										</button>
									</form>
								<?php else: ?>
									<?php if ($_item->getIsSalable()): ?>
										<button class="btn btn-add-to-cart"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></button>
									<?php else: ?>
										<button class="btn btn-add-to-cart"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></button>
									<?php endif; ?>
								<?php endif; ?>
							</div>
						<?php endif; ?>
						<ul class="add-to-links clearfix">
							<?php if ($showCompare): ?>
								<?php
									$compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
								?>
								<li class="compare"><a href="#"
								   title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
								   aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
								   data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_item); ?>'
								   role="button">
									<?php echo $block->escapeHtml(__('Compare')); ?>
									</a>
								</li>
							<?php endif; ?>
							<?php if ($showWishlist): ?>
								<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
									<li class="wishlist"><a href="#"
									   data-post='<?php echo $block->getAddToWishlistParams($_item); ?>'
									   data-action="add-to-wishlist"
									   title="<?php echo __('Add to Wishlist') ?>">
									   <?php echo $block->escapeHtml(__('Wishlist')); ?>
									</a></li>
								<?php endif; ?>
							<?php endif; ?>
						</ul>
						
						</div>
					</div>
			 <?php if($i % $rows == 0 || $i == $_collectionSize):?>
				</div>
			<?php endif;?>
		<?php endforeach;?>
	</div>
<?php if (!$block->isRedirectToCartEnabled()) : ?>
	<script type="text/x-magento-init">
	{
		"[data-role=tocart-form], .form.map.checkout": {
			"catalogAddToCart": {}
		}
	}
	</script>
<?php endif; ?>
