<?php
/**
 * Apptha
 * NOTICE OF LICENSE
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 * ==============================================================
 * MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category Apptha
 * @package Apptha_Marketplace
 * @version 1.2
 * @author Apptha Team <developers@contus.in>
 * @copyright Copyright (c) 2017 Apptha. (http://www.apptha.com)
 * @license http://www.apptha.com/LICENSE.txt
 */
?>
<?php
$OrderItemCollection = $block->getCollection();
$currencyCode = $block->getCurrencyCode();
$currencySymbol = $block->getCurrencySymbol($currencyCode );
foreach($OrderItemCollection as $item) {
    $sellerId = $item->getSellerId();
    $orderId = $item->getOrderId();
    $customerId = $item->getCustomerId();
    $sellerOrder[] = $block->getTodayOrder($orderId, $sellerId, $customerId, $flag = '1');
    $lastWeekOrder[] = $block->getLastWeekIncome($orderId, $sellerId, $customerId, $flag = '2');
    $lastMonthOrder[] = $block->getLastMonthIncome($orderId, $sellerId, $customerId, $flag = '3');
    $lastYearOrder[] = $block->getLastYearIncome($orderId, $sellerId, $customerId, $flag = '4');
}
$count = (!isset($sellerOrder) || is_null($sellerOrder)) ? '0' : count(array_filter($sellerOrder));
?>
<?php
/**
 * Todays Sales and today order count
 */
?>