<div class="popup_avaiable">
	<?php
	$qty = $block->getQtyP()?$block->getQtyP():1;
	$_imgHelper = $this->helper('Themevast\Themevast\Helper\ImageP');
	$_themeHelper = $this->helper('Themevast\Themevast\Helper\Data');
	$_checkoutHelper=$this->helper('Magento\Checkout\Helper\Data');
	$product=$block->getProducts();
	$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
	$cart = $objectManager->get('\Magento\Checkout\Model\Cart'); 
	$currencysymbol = $objectManager->get('Magento\Directory\Model\Currency');
	$symbol = $currencysymbol->getCurrencySymbol();
	$subTotal = (int)$cart->getQuote()->getSubtotal();
	$width = $subTotal/90*100 . '%';
	$grandTotal = $cart->getQuote()->getGrandTotal();
	$productUrl = $product->getProductUrl();
	$enable_image = true;
	if($enable_image) {
		$image_width  = 180;
		$image_height = 200;
		$_image = $_imgHelper->getImg($product, $image_width, $image_height, 'category_page_grid');
	}
	
	?>
	<div class="product_ajax">
		<p class="added"><?php echo __('%1 item(s) added to your cart.',$qty); ?></span></p>
		<div class="popup-details clearfix">
			<div class="col-sm-4">
				<?php if($enable_image && $_image) { ?>
					<div class="product_image">
						<a href="<?php echo $productUrl; ?>" title="<?php echo addslashes($_image->getLabel()); ?>"><img src="<?php echo $_image->getUrl(); ?>" alt="<?php echo addslashes($_image->getLabel()); ?>" /></a>
					</div>	
				<?php } ?>
			</div>
			<div class="col-sm-8">
				<h3><a href="<?php echo $productUrl; ?>"><?php echo $product->getName(); ?></a></h3>
				<div class="pop-price">
					<?php echo $block->getProductPrice($product); ?>
				</div>	
				
			</div>
		</div>
		<div class="actions clearfix">
			<a href="<?php echo $this->helper('Magento\Checkout\Helper\Cart')->getCartUrl(); ?>" class="button btn-viewcart" title="<?php echo __("Checkout");?>"><span><?php echo __("View Cart");?></span></a>
			<button onclick="jQuery.fancybox.close();" class="button btn-continue" title="<?php echo __("Continue Shopping");?>"><span><?php echo __("Continue Shopping");?></span></button>
		</div>
	</div>
</div>