<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Framework\View\Element\Template */
/** @var $helper \Magento\Search\Helper\Data */
$helper = $this->helper('Magento\Search\Helper\Data');
?>
<div class="block-search">
  <div class="block-content">
    <div class="dropdown">
      <div class="dropdown-toggle">
        <div class="top-search">
          <i class="fa fa-search"></i> 
        </div>
      </div>
      <div class="box-form-search">
        <div class="container">
          <form class="form minisearch dropdown-menu search-content" id="search_mini_form" action="<?php /* @escapeNotVerified */ echo $helper->getResultUrl() ?>" method="get">
            <div class="field search">
              <div class="control">
                <input id="search"
                      data-mage-init='{"quickSearch":{
                          "formSelector":"#search_mini_form",
                          "url":"<?php /* @escapeNotVerified */ echo $block->getUrl('search/ajax/suggest'); ?>",
                          "destinationSelector":"#search_autocomplete"}
                      }'
                      type="text"
                      name="<?php /* @escapeNotVerified */ echo $helper->getQueryParamName() ?>"
                      value="<?php /* @escapeNotVerified */ echo $helper->getEscapedQueryText() ?>"
                      placeholder="<?php /* @escapeNotVerified */ echo __('Search entire store here...'); ?>"
                      class="input-text"
                      maxlength="<?php /* @escapeNotVerified */ echo $helper->getMaxQueryLength();?>"
                      role="combobox"
                      aria-haspopup="false"
                      aria-autocomplete="both"
                      aria-expanded="false"
                      autocomplete="off"/>
                <button type="submit"
                        title="<?php echo $block->escapeHtml(__('Search')) ?>"
                        class="action search">
                  <span>
                    <?php /* @escapeNotVerified */ echo __('Search'); ?>
                  </span>
                </button>
              </div>
              <div id="search_autocomplete" class="search-autocomplete"></div>
              <?php echo $block->getChildHtml() ?>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
  <div class="menu-overlay"></div>
</div>
<script>
  require([
    'jquery'
  ], function ($) {
    'use strict';
    $( document ).ready(function() {
      $('.block-search .dropdown-toggle > .top-search').click(function(event){
        $(this).toggleClass('btn-close');
        $('.block-search .box-form-search').slideToggle();
        $('.block-search .menu-overlay').toggleClass('active');
        $('body').toggleClass('p-fix');
      });
    });
  });
</script>