<?php
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_Marketplace
 * @version     1.2
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2017 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 *
 */

/** @var  $block \Magento\Sales\Block\Order\Item\Renderer\DefaultRenderer */

if (file_exists("conf/conf.php")) 
  @include 'conf/conf.php';

$conn = new mysqli($conf->db->host, $conf->db->user, $conf->db->pass, $conf->db->name);

$_item = $block->getItem();
$order = $block->getOrder();

if(strstr($_SERVER['REQUEST_URI'], "return")) {
    $return = 1;
}
else {
    $return = 2;
}

$sellerGroupId = $customerId = $customerGroupId = $status = '';
$urlInterface = \Magento\Framework\App\ObjectManager::getInstance()->get('Magento\Framework\UrlInterface');
$currentUrl = $urlInterface->getCurrentUrl();
$helper = $this->helper('Apptha\Marketplace\Helper\Objectmanager');
$customerSession = $helper->customerSession();
$customerDatas = $customerSession->getCustomer();
if ($customerSession->isLoggedIn()) {
    $customerId = $customerSession->getId();
    $customerGroupId = $customerDatas->getGroupId();
    $helper = $this->helper('Apptha\Marketplace\Helper\Objectmanager');
    $sellerGroupData = $helper->customerSessionGroup($customerGroupId);
    $sellerGroupId = $sellerGroupData->getId();
    $status = $helper->sellerStatus($customerId);
}
$sellerId = $customerId;
$customerSession->getId();
$isInvoiced = $isShipped = $isBuyerCanceled = $isCanceled = $isRefunded = $isReturned = $isBuyerRefunded = $isBuyerReturned = 0;
if (!empty($sellerId)) {
    $sellerOrderDetails = $block->getSellerOrderDetails($_item, $order->getId(), $sellerId);
    $isInvoiced = $sellerOrderDetails->getIsInvoiced();
    $isShipped = $sellerOrderDetails->getIsShipped();    
    $sellerOrderItemDetails = $block->getSellerOrderItemDetails($_item, $order->getId(), $sellerId);
    $isBuyerCanceled = $sellerOrderItemDetails->getIsBuyerCanceled();
    $isCanceled = $sellerOrderItemDetails->getIsCanceled();
    $isReturned = $sellerOrderItemDetails->getIsReturned();
    $isRefunded = $sellerOrderItemDetails->getIsRefunded();
    $isBuyerReturned = $sellerOrderItemDetails->getIsBuyerReturned();
    $isBuyerRefunded = $sellerOrderItemDetails->getIsBuyerRefunded();
}
$product_name = $_item->getName();
$query = "SELECT mgkf_catalog_product_entity_int.value AS seller_id ";
$query .= "FROM mgkf_catalog_product_entity_int, mgkf_catalog_product_entity_varchar ";
$query .= "WHERE mgkf_catalog_product_entity_int.entity_id = mgkf_catalog_product_entity_varchar.entity_id ";
$query .= "AND mgkf_catalog_product_entity_int.attribute_id = 158 ";
$query .= "AND mgkf_catalog_product_entity_varchar.value = '".$product_name."' ";
$query .= "GROUP BY mgkf_catalog_product_entity_varchar.value";
$result = $conn->query($query);
$row_count = $result->num_rows;
$row_return = $result->fetch_row();
$seller_return = $row_return[0];

$query_return = "SELECT return_condition ";
$query_return .= "FROM mgkf_marketplace_seller_return_condition ";
$query_return .= "WHERE seller_id = '".$seller_return."'";
$result_return = $conn->query($query_return);
?>
<tr id="order-item-row-<?php /* @escapeNotVerified */ echo $_item->getId() ?>">
    <td class="col name"
        data-th="<?php echo $block->escapeHtml(__('Product Name')); ?>">
        <strong class="product name product-item-name">
            <?php echo $block->escapeHtml($_item->getName()) ?>
        </strong>
        <?php if ($_options = $block->getItemOptions()) { ?>
            <dl class="item-options">
            <?php foreach ($_options as $_option) { ?>
                <dt><?php echo $block->escapeHtml($_option['label']) ?></dt>
                <?php if (!$block->getPrintStatus()) { ?>
                    <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option)?>
                    <dd>
                        <?php if (isset($_formatedOptionValue['full_view'])) { ?>
                            <?php /* @escapeNotVerified */ echo $_formatedOptionValue['full_view']?>
                        <?php } else { ?>
                            <?php /* @escapeNotVerified */ echo $_formatedOptionValue['value']?>
                        <?php } ?>
                    </dd>
                <?php } else { ?>
                    <dd>
                        <?php echo nl2br($block->escapeHtml((isset($_option['print_value']) ? $_option['print_value'] : $_option['value'])))?>
                    </dd>
                <?php } ?>
            <?php } ?>
            </dl>
        <?php } ?>
        <?php $addtInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
        <?php if ($addtInfoBlock) { ?>
            <?php echo $addtInfoBlock->setItem($_item)->toHtml(); ?>
        <?php } ?>
        <?php echo $block->escapeHtml($_item->getDescription())?>
    </td>
    <td class="col sku"
        data-th="<?php echo $block->escapeHtml(__('SKU')); ?>"><?php /* @escapeNotVerified */ echo $block->prepareSku($block->getSku()) ?></td>
    <td class="col price"
        data-th="<?php echo $block->escapeHtml(__('Price')); ?>">
        <?php echo $block->getItemPriceHtml(); ?>
    </td>
    <td class="col qty"
        data-th="<?php echo $block->escapeHtml(__('Qty')); ?>">
        <ul class="items-qty">
            <?php if ($block->getItem()->getQtyOrdered() > 0) { ?>
                <li class="item"><span class="title"><?php /* @escapeNotVerified */ echo __('Ordered'); ?></span>
                    <span class="content">
                    <?php if($block->getItem()->getQtyOrdered()*1 > 1) { ?>
                        <input style="width:10%;" type="number" name="qty-order" value="<?php echo $block->getItem()->getQtyOrdered()*1; ?>" />
                    <?php } else { ?>
                        <?php /* @escapeNotVerified */ echo $block->getItem()->getQtyOrdered()*1 ?>
                    <?php } ?>
                    </span>
                </li>
            <?php } ?>
            <?php if ($block->getItem()->getQtyShipped() > 0) { ?>
                <li class="item"><span class="title"><?php /* @escapeNotVerified */ echo __('Shipped'); ?></span>
                    <span class="content"><?php /* @escapeNotVerified */ echo $block->getItem()->getQtyShipped()*1 ?></span>
                </li>
            <?php } ?>
            <?php if ($block->getItem()->getQtyCanceled() > 0 || $isCanceled == 1) { ?>
                <li class="item"><span class="title"><?php /* @escapeNotVerified */ echo __('Canceled'); ?></span>
                    <span class="content">
                        <?php /* @escapeNotVerified */
                        if ($isCanceled == 1) {
                            echo $block->getItem ()->getQtyOrdered () * 1;
                        } else {
                            echo $block->getItem ()->getQtyCanceled () * 1;
                        }         
                        ?>
                    </span>
                </li>
            <?php } ?>
            <?php if ($block->getItem()->getQtyRefunded() > 0) { ?>
                <li class="item"><span class="title"><?php /* @escapeNotVerified */ echo __('Refunded'); ?></span>
                    <span class="content">
                    <?php /* @escapeNotVerified */ echo $block->getItem ()->getQtyRefunded () * 1?></span>
                </li>
            <?php } ?>
            <?php if ($isReturned == 1) { ?>
                <li class="item"><span class="title"><?php /* @escapeNotVerified */ echo __('Returned'); ?></span>
                    <span class="content">
                    <?php /* @escapeNotVerified */ echo $block->getItem ()->getQtyOrdered () * 1?></span>
                </li>
            <?php } ?> 
        </ul>
    </td>    
    <td class="col subtotal"
        data-th="<?php echo $block->escapeHtml(__('Subtotal')); ?>">
        <?php echo $block->getItemRowTotalHtml(); ?>
        <?php
        $isSellerOrderManagement = $this->helper ( 'Apptha\Marketplace\Helper\System' )->getSellerOrderManagement ();
        $isReturnedorRefunded=$isReturned != 1 && $isRefunded != 1;
        if ($isSellerOrderManagement == 1 && ! empty ( $sellerId ) && $isCanceled != 1 && $isReturnedorRefunded) { ?>
            <br>
            <label style="display:none;"><?php echo __('Action').' : '; ?></label>
            <?php if($isBuyerCanceled == 1) { ?>
                <span><?php echo __('Cancel request sent'); ?></span>  
            <?php } elseif($isBuyerRefunded == 1) { ?>
                <span><?php echo __('Refund request sent'); ?></span>
            <?php } elseif($isBuyerReturned == 1) { ?>
                <span><?php echo __('Return request sent'); ?></span>    
            <?php } else { ?>
                <a href="javascript:void(0);" class="btn btn-primary"
                    onclick="document.getElementById('order_item_popup_<?php echo $_item->getId(); ?>').style.display = 'block';">        
                    <?php
                    if ($isInvoiced == 1 || $_item->getQtyOrdered () == $_item->getQtyInvoiced ()) {
                    echo __ ( 'Refund Item' );
                    } elseif ($isShipped == 1 || $_item->getQtyOrdered () == $_item->getQtyShipped ()) {
                    echo __ ( 'Return Item' );
                    } else {
                        echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('place_return')->toHtml();
                    }
                    ?>
                </a>
            <?php } ?> 
            <div class="order_item_action_popup"
                id="order_item_popup_<?php echo $_item->getId(); ?>"
                style="display: none;">
                <span style="float:right;"
                    onclick="document.getElementById('order_item_popup_<?php echo $_item->getId(); ?>').style.display = 'none';">X</span>
                <form action=""  method="post"  id="order_item_action_<?php echo $_item->getId(); ?>" enctype="multipart/form-data">
                    <label>
                        <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('reason')->toHtml();?>
                    </label>
                    <textarea name="reason" class="input-text required-entry"></textarea>
                    <input type="hidden" name="order_id" value="<?php echo $order->getId(); ?>" />
                    <input type="hidden" name="seller_id" value="<?php echo $seller_return; ?>" />
                    <input type="hidden" name="action" 
                            value="<?php if ($isInvoiced == 1 || $_item->getQtyOrdered () == $_item->getQtyInvoiced ()) {
                                echo 'refund';
                            } elseif ($isShipped == 1 || $_item->getQtyOrdered () == $_item->getQtyShipped ()) {
                                echo 'return';
                            } else {
                                echo 'cancel';
                            } ?>" />
                    <br><br>
                    <label>
                        <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('what_we_do_with_product')->toHtml();?>
                    </label>
                    <br>
                    <select name="choose_action">
                        <option selected><?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('choose')->toHtml();?></option>
                        <option value="money_back"><?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('get_my_money_back')->toHtml();?></option>
                        <option value="product_back"><?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('get_the_same_product')->toHtml();?></option>
                    </select>
                    <br><br>
                    <label>
                        <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('conditions')->toHtml();?>
                    </label>
                    <br>
                    <div class="conditions">
                        <?php
                        while($row_return = $result_return->fetch_assoc()) {
                            $condition = $row_return['return_condition'];
                            echo $condition . '<br>';   
                        }
                        ?>
                    </div>
                    <br>
                    <input type="checkbox" name="confirm_condition" value="confirm" required>
                    <label style="margin-right:10px;"><?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('confirm_conditions')->toHtml();?></label>
                    <br><br>
                    <input type="submit" class="btn btn-primary" name="submit" value="<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('submit')->toHtml();?>" /> 
                    <input type="button" onclick="document.getElementById('order_item_popup_<?php echo $_item->getId(); ?>').style.display = 'none';" class="btn btn-primary" name="cancel" value="<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('cancel')->toHtml();?>" />
                </form>
            </div>  
        <?php } ?>
    </td>
</tr>
<script>
require([
    'jquery',
    'mage/mage'
], function($){
    var dataFormOrderItem = $('#order_item_action_<?php echo $_item->getId(); ?>');
    var ignore = null;
    dataFormOrderItem.mage('validation', {
            ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
        }).find('input:text').attr('autocomplete', 'off');    
});
</script>