<?php
if (file_exists("conf/conf.php"))
    @include 'conf/conf.php';

$conn = new mysqli($conf->db->host, $conf->db->user, $conf->db->pass, $conf->db->name);

$sellerGroupId = $customerId = $customerGroupId = $status = '';
$urlInterface = \Magento\Framework\App\ObjectManager::getInstance()->get('Magento\Framework\UrlInterface');
$currentUrl = $urlInterface->getCurrentUrl();
$helper = $this->helper('Apptha\Marketplace\Helper\Objectmanager');
$customerSession = $helper->customerSession();
$customerDatas = $customerSession->getCustomer();
if ($customerSession->isLoggedIn()) {
    $customerId = $customerSession->getId();
    $customerGroupId = $customerDatas->getGroupId();
    $helper = $this->helper('Apptha\Marketplace\Helper\Objectmanager');
    $sellerGroupData = $helper->customerSessionGroup($customerGroupId);
    $sellerGroupId = $sellerGroupData->getId();
    $status = $helper->sellerStatus($customerId);
}
$query = "SELECT increment_id, mgkf_sales_order.created_at, mgkf_marketplace_sellerorderitems.product_name, grand_total, mgkf_sales_order.status ";
$query .= "FROM mgkf_sales_order, mgkf_marketplace_sellerorderitems ";
$query .= "WHERE entity_id = order_id ";
$query .= "AND mgkf_sales_order.status LIKE '%return%' ";
$query .= "AND seller_id = '".$customerId."'";
$result = $conn->query($query);
$count = $result->num_rows;
?>
<?php if (is_array($result) || is_object($result)) { ?>
    <input type="hidden" id="count" value="<?php echo $count; ?>" />
    <h3 class="font-weight-bold mt-3">
        <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('returns')->toHtml(); ?>
    </h3>
    <div class="box-table mb-5">
        <?php
        $i = 0;
        while ($row = $result->fetch_assoc()) {
            $order_id = $row['increment_id'];
            $date = $row['created_at'];
            $product_name = $row['product_name'];
            $total = $row['grand_total'];
            $status = ucfirst($row['status']);

            $query_info = "SELECT entity_id, quote_id, state, status, awb_number, courier, cancelling_reason, shipping_amount, grand_total, customer_firstname, customer_lastname, customer_email ";
            $query_info .= "FROM mgkf_sales_order ";
            $query_info .= "WHERE increment_id = '".$order_id."'";
            $result_info = $conn->query($query_info);
            $row_info = $result_info->fetch_assoc();
            $quoteId = $row_info['quote_id'];
            $awbNumber = $row_info['awb_number'];
            $courier = $row_info['courier'];
            $shippingAmount = number_format($row_info['shipping_amount'], 2, '.', '');
            $grandTotal = number_format($row_info['grand_total'], 2, '.', '');
            $customerFirstname = $row_info['customer_firstname'];
            $customerLastname = $row_info['customer_lastname'];
            $customerEmail = $row_info['customer_email'];

            $query_return = "SELECT reason, return_action ";
            $query_return .= "FROM mgkf_marketplace_return_order ";
            $query_return .= "WHERE seller_id = $customerId ";
            $query_return .= "AND order_increment_id = '" . $order_id . "'";
            $result_return = $conn->query($query_return);
            $row_return = $result_return->fetch_assoc();
            $reason = $row_return['reason'];
            $return_action = $row_return['return_action'];
            if ($return_action == 'money_back') {
                $return_action = 'Returnarea banilor';
            }
            if ($return_action == 'product_back') {
                $return_action = 'Trimiterea aceluiasi produs';
            }
        ?>
            <div class="row gy-3 flex-column mb-3">
                <div class="col-12">
                    <div class="shadow py-3 px-4">
                        <h5 class="m-0">
                            <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('order_nr')->toHtml(); ?>.
                            <span class="text-uppercase">
                                <?php echo $order_id; ?>
                            </span>
                        </h5>
                        <div class="row mt-2 align-items-md-center">
                            <div class="col-xl-10">
                                <div class="row flex-column">
                                    <div class="col-xl-9">
                                        <div class="row">
                                            <div class="col-md-4">
                                                <p class="m-0 font-weight-bold">
                                                    <?php echo __('Date'); ?>:
                                                    <span class="font-weight-normal">
                                                        <?php echo $date; ?>
                                                    </span>
                                                </p>
                                            </div>
                                            <div class="col-md-4">
                                                <p class="m-0 font-weight-bold">
                                                    <?php echo __('Status'); ?>:
                                                    <span class="badge bg-danger">
                                                        <?php
                                                        if($status == 'Return_completed') $status = $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('completed')->toHtml();
                                                        if($status == 'Return_taken') $status = $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('taken')->toHtml();
                                                        if($status == 'Returned') $status = $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('sent')->toHtml();
                                                        echo $status;
                                                        ?>
                                                    </span>
                                                    <br>
                                                    <?php 
                                                    if($status != 'Finalizată' && $status != 'Completed') {
                                                    ?>
                                                        <button type="button" class="badge bg-primary" onclick="show_statuses(<?php echo $i; ?>);">
                                                            <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('change_status')->toHtml(); ?>
                                                        </button>
                                                        <div id="possible-statuses-<?php echo $i; ?>" style="display:none;">
                                                            <form method="post" action="/sellerOrders.php">
                                                                <input type="hidden" name="order_id" value="<?php echo $order_id; ?>" />
                                                                <input type="hidden" id="url" name="url" value="<?php echo $currentUrl; ?>">
                                                                <?php
                                                                if($status == 'Trimis' || $status == 'Sent') {
                                                                ?>
                                                                    <button type="submit" class="badge bg-info" name="return_taken">
                                                                        <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('taken')->toHtml(); ?>
                                                                    </button>
                                                                <?php
                                                                }
                                                                if($status == 'Preluat' || $status == 'Taken') {
                                                                ?>
                                                                    <button type="submit" class="badge bg-info" name="return_completed">
                                                                        <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('completed')->toHtml(); ?>
                                                                    </button>
                                                                <?php
                                                                }
                                                                ?>
                                                            </form>
                                                        </div>
                                                    <?php
                                                    }
                                                    ?>                                                    
                                                </p>
                                            </div>
                                            <div class="col-md-4">
                                                <p class="m-0 font-weight-bold">
                                                    <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('product_details')->toHtml(); ?>:
                                                    <span class="font-weight-normal">
                                                        <?php echo $product_name; ?>
                                                    </span>
                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-12">
                                        <p class="m-0 font-weight-bold">
                                            <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('total_products_amount')->toHtml(); ?>:
                                            <span class="font-weight-normal">
                                                <?php echo number_format($total, 2, '.', ''); ?>
                                            </span>
                                        </p>
                                    </div>
                                </div>
                            </div>
                            <div class="col-12 col-sm-8 col-md-6 col-xl-2 text-md-right mt-3 mt-xl-0">
                                <button class="show-return-details btn btn-outline-danger btn-block py-1 text-uppercase shadow-none font-weight-bold font-15" data-tab="details-<?php echo $order_id; ?>">
                                    <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('return_info')->toHtml(); ?>
                                </button>
                            </div>
                        </div>
                        <div id="details-<?php echo $order_id; ?>" class="d-none return-details mt-3">
                            <hr>
                            <p><b>AWB: </b><?php echo $awbNumber; ?></p>
                            <p><b><?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('courier')->toHtml(); ?>: </b><?php echo $courier; ?></p>
                            <?php
                            if($shippingAmount != '') {
                            ?>
                                <p><b><?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('shipping_price')->toHtml(); ?>: </b><?php echo $shippingAmount; ?></p>
                            <?php
                            }
                            ?>                            
                            <p><b><?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('total')->toHtml(); ?>: </b><?php echo $grandTotal; ?></p>
                            <p><b><?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('customer_first_last_name')->toHtml(); ?>: </b><?php echo $customerFirstname . ' ' . $customerLastname; ?></p>
                            <p><b><?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('email')->toHtml(); ?>: </b><?php echo $customerEmail; ?></p>
                            <p>
                                <span class="font-weight-bold">
                                    <?php echo 'Motivul returului:'; ?>
                                </span>
                                <span class="font-weight-normal">
                                    <?php echo $reason; ?>
                                </span>
                            </p>
                            <p>
                                <span class="font-weight-bold">
                                    <?php echo 'Ce dorește clientul: '; ?>
                                </span>
                                <span class="font-weight-normal">
                                    <?php echo $return_action; ?>
                                </span>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        <?php
            $i++;
        }
        ?>
    </div>
<?php
} else {
    echo __('No records found');
}
?>
<script>
var tabLink = document.querySelectorAll(".show-return-details");
var tabContent = document.querySelectorAll(".return-details");

tabLink.forEach((el) => {
  el.addEventListener("click", showReturnDetails);
});

function showReturnDetails(el) {
var content = el.currentTarget.dataset.tab;
    tabContent.forEach((el) => {
       el.classList.remove("d-block");
    });
    document.querySelector("#" + content).classList.add("d-block");
}

function show_statuses(k) {
    var count = document.getElementById("count").value;
    for(var i=0; i<=count; i++) {
        if(document.getElementById("possible-statuses-"+i)) {
            document.getElementById("possible-statuses-"+i).style.display = "none";
        }
    }
    document.getElementById("possible-statuses-"+k).style.display = "block";
}
</script>