<?php
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_Marketplace
 * @version     1.2
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2017 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 *
 */
if (file_exists("conf/conf.php")) 
  @include 'conf/conf.php';

$conn = new mysqli($conf->db->host, $conf->db->user, $conf->db->pass, $conf->db->name);

$sellerGroupId = $customerId = $customerGroupId = $status = '';
$urlInterface = \Magento\Framework\App\ObjectManager::getInstance()->get('Magento\Framework\UrlInterface' );
$currentUrl = $urlInterface->getCurrentUrl();
$helper = $this->helper('Apptha\Marketplace\Helper\Objectmanager');
$customerSession = $helper->customerSession();
$customerDatas = $customerSession->getCustomer();
if ($customerSession->isLoggedIn()) {
    $customerId = $customerSession->getId();
    $customerGroupId = $customerDatas->getGroupId();
    $helper = $this->helper('Apptha\Marketplace\Helper\Objectmanager');
    $sellerGroupData = $helper->customerSessionGroup($customerGroupId);
    $sellerGroupId = $sellerGroupData->getId();
    $status = $helper->sellerStatus( $customerId);
}
$searchProductName = $this->getRequest()->getParam('name');
$searchProductStatus = $this->getRequest()->getParam('status');
$searchProductPrice = $this->getRequest()->getParam('price');
$searchProductSku = $this->getRequest()->getParam('sku');
$searchProductType = $this->getRequest()->getParam('type');
$delete = $this->getRequest()->getParam('multi');
$entityIds = $this->getRequest()->getParam('id');
$multisubmit = $this->getRequest()->getParam('multi_submit');
$productDeleteOption = $block->getProductDeleteApproval();
$productBulkOption = $block->getProductBulkApproval();
$dataHelper = $this->helper('Apptha\Marketplace\Helper\Data');
$sellerBlock = $dataHelper->getSellerDetails();

if ($customerId == 10 || $customerId == 11) { ?> 
    <h3>Manage Invoices</h3>
    <div class="col-md-12">
        <h3><b><?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('invoices')->toHtml();?></b></h3>
        <?php
        $query_vendor = "SELECT email, firstname, lastname ";
        $query_vendor .= "FROM mgkf_customer_entity ";
        $query_vendor .= "WHERE entity_id = 7";
        $result_vendor = $conn->query($query_vendor);

        $query = "SELECT * FROM mgkf_marketplace_seller_invoices ORDER BY date";
        $result = $conn->query($query);

        $query_inv = "SELECT * ";
        $query_inv .= "FROM mgkf_marketplace_sellerorder, mgkf_customer_entity ";
        $query_inv .= "WHERE seller_id = entity_id ";
        $query_inv .= "AND active = 0";
        $result_inv = $conn->query($query_inv);

        print ('
        <table class="table">
            <thead>
                <tr> ');
                echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('db_transaction')->toHtml();
            print ('
                </tr>
            </thead>
            <tbody> 
            ');
        if ($result->num_rows > 0) {         
            $sum = 0;
            $i = 1;
            while($row = $result->fetch_assoc()) {                 
                $pr = '%';
                print('
                    <tr>
                        <td>'.$i.'</td>
                        <td>'.$row['date'].'</td>
                        <td>'.number_format((float)$row['total'], 2, '.', '').'</td>
                        <td>
                            <a href="#" title="View Invoice" class="" data-toggle="modal" data-target="#myModal"><i class="fa fa-eye" aria-hidden="true"></i></a>
                            &#160;&#160;&#160;
                            <a href="#" title="Download Invoice"><i class="fa fa-download" aria-hidden="true"></i></a>
                            &#160;&#160;&#160;
                        </td>
                    </tr>
                    ');
                    $i++;
                }              
                print('</tbody>
        </table>
        <hr>        
        ');
        }   
        ?>
    </div>
    <?php
    $query_inv = "SELECT * ";
    $query_inv .= "FROM mgkf_marketplace_sellerorder, mgkf_customer_entity ";
    $query_inv .= "WHERE seller_id = entity_id ";
    $query_inv .= "AND active = 0";
    $result_inv = $conn->query($query_inv);
    ?>
    <div class="modal fade" id="myModal" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button> 
                    <div class="col-md-12">
                        <div class="col-md-6">             
                            <div class="header-left">
                                <div class="logo-left">
                                    <img width="150" height="100" src="pub/media/logo/stores/1/Screenshot_2019-03-18_at_16.37.53.png" alt="Atytude" />
                                </div>
                                <div class="business-information">
                                    <p>
                                        <b>Address: Fashion Marketplace SRL </b>str. Aleea Compozitorilor nr. 15
                                        bl. 821, sc. A, et. 8, ap. 33 sect. 6 Bucuresti, Romania
                                    </p>
                                    <p><b>Phone:</b> +40666888111000</p>
                                    <p><b>Tax ID:</b> 37616574</p>
                                    <p><b>Contact:</b> support@tukan.ro</p>
                                    <p><b>Registered:</b> J40/7422/2017</p>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="header-right">
                                <div class="info">
                                    <h1 class="info-title">INVOICE</h1>
                                    <p>Invoice <b>#0000000001</b></p>
                                    <p>Date: <b>Aug 03, 2019</b></p>
                                    <p>Amount = <b>1111.50</b></p>
                                    <p>Currency: <b>RON</b></p>
                                    <p class="mp-invoice-barcode">
                                        <barcode code="000000000001" type="C39"/>
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>                            
                </div>
                <div class="modal-body">
                    <ul>
                        <li>                   
                            <div class="address">
                                <div class="col-md-12">
                                    <div class="col-md-6">
                                        <div class="billing-address">
                                            <?php while($row = $result_vendor->fetch_assoc()) { ?>
                                                <h3 class="mp-block-heading">Client's Personal Data</h3>
                                                <p><b><?php echo $row['firstname'] .' '. $row['lastname'] ?></b></p>
                                                <p><b><?php echo $row['email'] ?></b></p>
                                            <?php } ?>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="payment-method">
                                            <h3 class="mp-block-heading">Payment Method</h3>
                                            <br><br>
                                            <p><b>Card Transfer</b></p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </li>                                
                    </ul>
                    <br><br><br><br><br><br><br><br>
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th>Nr</th>
                                <th>Product Name</th>
                                <th>U.M.</th>
                                <th>Qty</th>               
                                <th>Value</th>  
                                <th>TVA</th>
                                <th>Total</th>              
                            </tr>
                        </thead>
                        <tbody> 
                        <?php
                        $i=1;
                        $sum=0;
                        $total_value=0;
                        $total_tva=0;
                        $total_total=0;
                        while($row = $result_inv->fetch_assoc()) {
                            $curr = 'RON';
                            $qty = 1;
                            $tva = $row['tva'];
                            $com = $row['commission'];
                            $total = $com*(1+$tva*0.01);
                            $tva_converted = $tva * 0.1;
                            $tva_value = $total - $com;
                            $total_value = $total_value + $com;
                            $total_tva = $total_tva + $tva_value;
                            $total_total = $total_total + $total;
                            print('
                            <tr>
                                <td>'.$i.'</td>
                                <td>Commission Transaction '.$row['firstname'].' '. $row['lastname'].'</td>
                                <td>buc</td>
                                <td>'.$qty.'</td>                
                                <td>'.number_format((float)$com, 2, '.', '').'</td>
                                <td>'.number_format((float)$tva_value, 2, '.', '').'</td>
                                <td>'.number_format((float)$total, 2, '.', '').'</td>
                            </tr>
                            ');
                            $i++;
                        } ?>
                            <tr>
                                <td class="right" colspan="4"><b>Total:</b></td>
                                <td class="right"><?php echo number_format((float)$total_value, 2, '.', '') ?></td>
                                <td class="right"><?php echo number_format((float)$total_tva, 2, '.', '') ?></td>
                                <td class="right"><?php echo number_format((float)$total_total, 2, '.', '') ?></td>
                            </tr>                                
                        </tbody>
                    </table>        
                    <div class="footer-left">
                        <div class="col-md-12">
                            <h3 class="mp-note">Notes:</h3>
                            <span style="font-style: italic;">TVA is 19%</span>
                            <br><br>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button onclick="window.print();" type="button" class="btn btn-primary hidden-print"><span class="glyphicon glyphicon-print" aria-hidden="true"></span>   Print Invoice</button>        
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>    
        </div>
    </div>
    <?php
    }
    else {
    ?>
    <div class="product-manage">
        <div id="filter_div" class="deactive">
            <form class="form search" action="" id="search-form" method="post">
                <?php if($productDeleteOption == 1) { ?>
                    <div class="mp_action">
                        <b><?php echo __('Action'); ?></b> 
                        <select name="multi"class="multi-action" id="multi">
                            <option name="" value="Select an option">
                                <?php echo __('Select an option'); ?>
                            </option>
                            <?php
                            /**
                            * Display delete option
                            */
                            ?>
                            <option name="delete" value="delete">
                                <?php echo __('Delete'); ?>
                            </option>
                        </select>
                        <div class="form_submit_btn">
                            <button type="submit" class="button multi_submit"
                                onclick="document.getElementById('multi_submit').value='1'; "
                                title="<?php echo __('Submit') ?>"
                                name="multi_submit" id="multi_submit">
                                <span>
                                    <span>
                                        <?php echo __('Submit') ?>
                                    </span>
                                </span>
                            </button>
                        </div>
                    </div>
                    <script>
                    require([
                            "jquery",
                            "mage/calendar"
                        ], function($) {
                        $('#search-form').on('keyup keypress', function(e) {
                                var keyCode = e.keyCode || e.which;
                                if (keyCode === 13) { 
                                e.preventDefault();
                                return false;
                                }
                            });
                        var selectoption;
                            $('.multi_submit').click(function() {
                            selectoption=$("#multi option:selected").val();
                            if(selectoption=="delete"){
                                    if($('.product-ids').is(":checked")){
                                            return true;
                                    }
                                    else{
                                        alert("<?php echo __('Please Select Products')?>");
                                        return false;
                                        }
                            }
                            else{
                                    alert("<?php echo __('Please Select Action')?>");
                                    return false;
                            }
                            });

                        });
                    </script>
                <?php } ?>
                <fieldset class="fieldset">
                    <div class="fieldset_form">
                        <div class="field name ">
                            <label class="label" for="name"><span><?php echo __('Name') ?></span></label>
                            <div class="control">
                                <input name="name" id="name" title="<?php echo __('Name') ?>" class="input-text" type="text" value="<?php if($searchProductName != "") {echo $searchProductName; } ?>" />
                            </div>
                        </div>
                        <div class="field name ">
                            <label class="label" for="status">
                                <span>
                                    <?php echo __('Status') ?>
                                </span>
                            </label>
                            <div class="control">
                                <select name="status" class="select" id="status">
                                    <option value=""><?php echo __('All'); ?></option>
                                    <option value="1"
                                        <?php if($searchProductStatus != "" && $searchProductStatus == '1') {echo 'selected="selected"';}?>><?php echo __('Enabled'); ?></option>
                                    <option value="2"
                                        <?php if($searchProductStatus != "" && $searchProductStatus == '2') {echo 'selected="selected"';}?>><?php echo __('Disabled'); ?></option>
                                </select>
                            </div>
                        </div>
                        <div class="field type ">
                            <label class="label" for="type">
                                <span>
                                    <?php echo __('Type') ?>
                                </span>
                            </label>
                            <div class="control">
                                <select name="type" class="select" id="type">
                                    <option value=""><?php echo __('All'); ?></option>
                                    <option value="simple"
                                        <?php if($searchProductType != "" && $searchProductType == "simple") {echo 'selected="selected"';}?>><?php echo __('Simple'); ?></option>
                                    <option value="virtual"
                                        <?php if($searchProductType != "" && $searchProductType == "virtual") {echo 'selected="selected"';}?>><?php echo __('Virtual'); ?></option>
                                </select>
                            </div>
                        </div>
                        <div class="field price ">
                            <label class="label" for="price">
                                <span>
                                    <?php echo __('Price') ?>
                                </span>
                            </label>
                            <div class="control">
                                <input type="text" name="price" id="price" class="input-text" value="<?php if($searchProductPrice != "") { echo $searchProductPrice; }?>" />
                            </div>
                        </div>
                        <div class="field sku ">
                            <label class="label" for="sku">
                                <span>
                                    <?php echo __('SKU') ?>
                                </span>
                            </label>
                            <div class="control">
                                <input type="text" name="sku" id="sku" class="input-text" value="<?php if($searchProductSku != "") { echo $searchProductSku; }?>" />
                            </div>
                        </div>
                    </div>
                    <button type="submit" title="<?php echo __('Search') ?>" class="product-search"><?php echo __('Search');?></button>
                </fieldset>
                <div class="product-url">
                    <a href="<?php echo $block->getAddProductUrl(); ?>" class="action submit primary">
                        <?php echo __('Add New Product'); ?>
                    </a>
                </div>
                <?php
                $productCollection = $block->getCollection();
                if ($productCollection->getSize() > 0) { ?>
                    <div class="toolbar top">
                        <?php echo $block->getPagerHtml(); ?>
                    </div>
                    <table class="manage-product-table">
                        <tr class="header" style="background: #ddd;">
                            <?php if($productDeleteOption == 1) { ?>
                            <th><?php echo __('#')?></th>
                            <?php } ?>
                            <th><?php echo __('Thumbnail'); ?></th>
                            <th><?php echo __('Name'); ?></th>
                            <th><?php echo __('Type'); ?></th>
                            <th><?php echo __('SKU'); ?></th>
                            <th><?php echo __('Price'); ?></th>
                            <th><?php echo __('Quantity'); ?></th>
                            <th><?php echo __('State'); ?></th>
                            <th><?php echo __('Status'); ?></th>
                            <th><?php echo __('Action'); ?></th>
                        </tr>
                        <?php $count = $productCollection->getSize ();
                            $productCollection = $productCollection->getData();
                            for ($i = 0; $i < $count; $i++) {
                                $productRepository = $block->getProductCollection(); 
                                $productId = $productCollection[$i]['entity_id'];
                                $product = $productRepository->getById($productId); 
                                $minimumQuantity = $block->getStockItem();
                                $productId = $product->getEntityId();
                                $minimumQuantity = $block->getStockItem();
                            ?>
                        <tr>
                        <?php if($productDeleteOption == 1) { ?>
                            <td>
                                <input type="checkbox" name="id[]" id="id" class="product-ids" value="<?php echo $product->getId(); ?>" />
                            </td>
                        <?php } ?>
                        <td>
                            <?php
                            $imagehelper = $this->helper('Magento\Catalog\Helper\Image');
                            $productImage = $imagehelper->ini ($product, 'category_page_list')->constrainOnly ( FALSE )->keepAspectRatio ( TRUE )->keepFrame ( FALSE )->resize ( 200 )->getUrl ();
                            ?>
                            <?php if($product->getStatus() == 1) { ?>
                            <a href="<?php echo $product->getProductUrl(); ?>" title="<?php echo $product->getName(); ?>"> 
                                <img src="<?php echo $productImage; ?>" />
                            </a>  
                            <?php
                            } else { ?>
                                <img src="<?php echo $productImage; ?>" />
                            <?php } ?>
                        </td>
                        <td>
                        <?php if($product->getStatus() == 1) { ?>
                            <a href="<?php echo $product->getProductUrl(); ?>"><?php echo $product->getName(); ?></a>
                            <?php
                            } else {
                                echo $product->getName ();
                            }
                            ?>
                        </td>
                        <td><?php echo ucfirst($product->getTypeId()); ?></td>
                        <td><?php echo $product->getSku(); ?></td>
                        <td>
                            <?php
                            $helper = $this->helper('Apptha\Marketplace\Helper\Objectmanager');
                            echo  $helper->productPrice($product );
                            ?>
                        </td>
                        <td>
                            <?php
                            if($this->getProductQty($product->getId ()) >= $minimumQuantity) {
                                echo $this->getProductQty($product->getId());
                            } elseif ($this->getProductQty($product->getId()) < $minimumQuantity && $this->getProductQty ( $product->getId () ) != 0 && $product->getTypeId() !='configurable'){
                                echo $this->getProductQty($product->getId());?> 
                                <div class="stock available">
                                    <span>
                                        <?=  __('Low stock') ?>
                                    </span>
                                </div>
                            <?php 
                            } elseif ($this->getProductQty($product->getId()) == 0 && $product->getTypeId() !='configurable'){
                                echo $this->getProductQty($product->getId());?>
                                <div class="stock unavailable">
                                    <span>
                                        <?= __('Out Of stock') ?>
                                    </span>
                                </div>
                            <?php } else {
                                echo '-';
                            }
                            ?>
                        </td>
                        <td>
                            <?php
                            if ($product->getProductApproval() == 1) {
                                echo __ ( 'Approved' );
                            } else {
                                echo __ ( 'Disapproved' );
                            }
                            ?>
                        </td>
                        <td>
                            <?php
                            if ($product->getStatus() == 1) {
                                echo __ ( 'Enabled' );
                            } else {
                                echo __ ( 'Disabled' );
                            }
                            ?>
                        </td>
                        <td>
                            <a href="<?php echo $block->getPrductEditUrl($product->getId()); ?>">
                                <span>
                                    <?php echo __('Edit'); ?>
                                </span>
                            </a>
                            <?php if($productDeleteOption){?>
                            <a href="<?php echo $block->getProductDeleteUrl($product->getId()); ?>" onclick="return confirm('<?php
                                /**
                                * confirming message before delete
                                */
                                echo __ ( 'Are you sure want to delete?' );
                                ?>');">
                                <span>
                                    <?php echo __('Delete'); ?>
                                </span>
                            </a>
                            <?php }?>
                        </td>
                    </tr>
                    <?php } ?>
                </table>
                <div class="toolbar-bottom">
                    <div class="toolbar bottom">
                        <?php echo $block->getPagerHtml(); ?>
                    </div>
                </div>
                <?php } else { ?>
                    <br>
                    <p><?php echo __("We couldn't find any records."); ?></p>
                <?php } ?>
            </div>
        </form>
    </div>
    <?php
    /**
     * Bulk product upload form
     */
    ?>
<?php if($productBulkOption && !empty($sellerBlock ->getStoreName())) { ?>
<label>
    <span class="bulk-upload-title">
        <b><?php echo __('Bulk Product Upload'); ?></b>
    </span>
    <a href="<?php echo $block->getViewFileUrl('Apptha_Marketplace::sampleproducts.csv'); ?>" download>
        <?php echo __('[Download Sample CSV]'); ?>
    </a>
    </label>
    <form name="bulk-product-upload-form" id="bulk-product-upload-form" class="bulk-product-upload-form" onsubmit="return bulkProductUploadValidate(this);" method="post" action="<?php echo $this->getBulkUploadUrl(); ?>" enctype="multipart/form-data">
        <label for="bulk-product-upload-csv-file" class="required bulk-product-upload-csv-file">
            <?php echo __('Upload CSV File'); ?>
        </label>
        <div class="input-box">
            <input type="file" class="required-file bulk-product-upload-file" id="bulk-product-upload-csv-file" name="bulk-product-upload-csv-file" accept=".csv" />
            <div>
                <small>
                    <?php echo __('Upload .csv format'); ?>
                </small>
            </div>
        </div>
        <label for="bulk-product-upload-image-file" class="bulk-product-upload-image-file">
            <?php echo __('Upload Image File'); ?>
        </label>
        <div class="input-box">
            <input type="file" class="bulk-product-upload-file" id="bulk-product-upload-image-file" name="bulk-product-upload-image-file" accept=".zip" />
            <div>
                <small>
                    <?php echo __('Upload .zip format'); ?>
                </small>
            </div>
        </div>
        <button type="submit" class="button bulk-upload-submit" title="<?php echo __('Upload') ?>" name="bulk-upload-submit" id="bulk-upload-submit" class="bulk-upload-submit">
            <span>
                <span>
                    <?php echo __('Upload') ?>
                </span>
            </span>
        </button>
    <?php } ?>
<?php } ?>