<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<?php
/**
 * Language switcher template
 */
?>
<?php if (count($block->getStores())>1) { ?>
<?php $id = $block->getIdModifier() ? '-' . $block->getIdModifier() : ''?>
<li class="d-block nav-item border-top-small-sm dropdown m-0" id="switcher-language<?php /* @escapeNotVerified */ echo $id?>">
   <a class="nav-link text-dark dropdown-toggle py-2 px-3 px-lg-1" id="switcher-language-trigger<?php /* @escapeNotVerified */ echo $id?>" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
   <span class="d-block position-relative d-lg-inline view__click view-<?php echo $block->escapeHtml($block->getCurrentStoreCode()) ?>">
   <?php echo $block->escapeHtml($block->getStoreName()) ?>
   </span>
   </a>
   <div class="border-0 dropdown-menu menu-2 m-0 rounded-0">
      <ul class="p-0 m-0">
         <?php foreach ($block->getStores() as $_lang) { ?>
         <?php if ($_lang->getId() != $block->getCurrentStoreId()) { ?>
         <li class="view-<?php echo $block->escapeHtml($_lang->getCode()); ?> switcher-option">
            <a class="dropdown-item lang-flag" style="background-image:url('<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/flags/'. $_lang->getCode() . '.png') ?>');" href="<?php echo $_lang->getCurrentUrl(false) ?>" data-post='<?php /* @escapeNotVerified */ echo $block->getTargetStorePostData($_lang); ?>'>
            <?php echo $block->escapeHtml($_lang->getName()) ?>
            </a>
         </li>
         <?php } ?>
         <?php } ?>
      </ul>
   </div>
</li>
<?php } ?>