<?php 
use Magento\Framework\App\Action\Action;
if($this->getConfigSys('enabled')){?>
<?php $_productCollection = $this->getProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$random_string = $this->generateRandomString(10);
$idDeal = 'dealslider_'.$this->getConfig('identify','tv');
$productfirst=$_productCollection->getFirstItem();
$show_time=true;
	?>
<div id="<?php echo $idDeal?>">
	<div class="deal_preload"></div>
    <div class="hotdeal">	
		<?php			
			if ($block->getMode() == 'grid') {
				$viewMode = 'grid';
				$image = 'category_page_grid';
				$showDescription = false;
				$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
			} else {
				$viewMode = 'list';
				$image = 'category_page_list';
				$showDescription = true;
				$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
			}
			$pos = $block->getPositioned();
			
		?>
		<?php if($this->getConfig('title',$this->getConfigSys('title'))){?>
			<div class="title-product-heading title-onsale-heading">
				<h2><?php echo $this->getConfig('title',$this->getConfigSys('title')) ?></h2>
				<p class="des"><?php echo __('Lorem Ipsum is simply dummy text of the printing and typesetting industry.') ?></p>
			</div>
		<?php }?>
		<?php if(!$_productCollection->getSize()): ?> 
			<div class="message info empty">	
				<p class="note-msg"><?php echo __('There are no products matching the selection.') ?></p>
			</div>
		<?php else: ?>
			<?php
			if(!$rows = $this->getConfigSys('row_show'))
				$rows = 1;
			?>	
			<div class="row">
				  <?php // Timer  ?>
					<?php if( isset($productfirst) && $productfirst->getFinalPrice() < $productfirst->getPrice() && $show_time && $productfirst->getSpecialToDate()!=''){
						$date = date('G:i:s', strtotime($productfirst->getSpecialToDate()));
						if ($date == "0:00:00") {
							$targetDate = date('m/d/Y \2\3\:\5\9\:\0\0', strtotime($productfirst->getSpecialToDate()));
						}else{
							$targetDate = date('m/d/Y G:i:s', strtotime($productfirst->getSpecialToDate()));
						}
						?>
						<div class="deal-timmer">
							<div id="deal-<?php echo $random_string ?>" class="item deal-time"></div>
							<script type="text/javascript">
								require(['jquery','themevast/datetime'],function () {
									jQuery("#deal-<?php echo $random_string ?>").CustomDate({
										targetDate:"<?php echo $targetDate; ?>",
										displayFormat:"<span class='countdown-section'><span class='countdown-amount'>%%D%%</span><span class='countdown-period'><?php echo __('Days') ?></span></span><span class='countdown-section'><span class='countdown-amount'>%%H%%</span><span class='countdown-period'><?php echo __('Hrs') ?></span></span><span class='countdown-section'><span class='countdown-amount'>%%M%%</span><span class='countdown-period'><?php echo __('Mins') ?></span></span><span class='countdown-section'><span class='countdown-amount'>%%S%%</span><span class='countdown-period'><?php echo __('Secs') ?></span></span>",
									});
								});
							</script>
						</div>
					<?php } ?>
					<?php // End Time?>
				<div class="view_all"><a href="<?php echo $this->getUrl('hotdeal')?>" alt="View All"><?php echo __("View All");?></a></div>
				<div class="owl">
					<?php $_collectionSize = $_productCollection->count() ?>
					<?php $i=0; foreach ($_productCollection as $_product): ?>
						<?php if($i %$rows == 0) echo "<div class='item deal_item'>"; ?>

							<div class="product-item">
							
								<?php
								$productImage = $block->getImage($_product, $image);
								if ($pos != null) {
									$position = ' style="left:' . $productImage->getWidth() . 'px;'
										. 'top:' . $productImage->getHeight() . 'px;"';
								}
								?>
								<?php // Product Image ?>
								<div class="product-photo">
									<!--- End -->
										<div class="new-sale-label">
											<?php
											$specialprice = $_product->getSpecialPrice();
											$specialPriceFromDate = $_product->getSpecialFromDate();
											$specialPriceToDate = $_product->getSpecialToDate();

											$today = time();
											if ($specialprice) {
												if ($today >= strtotime($specialPriceFromDate) && $today <= strtotime($specialPriceToDate) || $today >= strtotime($specialPriceFromDate) && is_null($specialPriceToDate)) { ?>
													<span class="label-product label-sale"><?php echo __('Sale'); ?></span>
												<?php }
											}
											?>
											<?php
											$now = date("Y-m-d");
											$newsFrom = substr($_product->getNewsFromDate(), 0, 10);
											$newsTo = substr($_product->getNewsToDate(), 0, 10);

											if (($newsTo != '' || $newsFrom != '')&&(!$specialprice)) {
											if (($newsTo != '' && $newsFrom != '' && $now >= $newsFrom && $now <= $newsTo) || ($newsTo == '' && $now >= $newsFrom) || ($newsFrom == '' && $now <= $newsTo)) {?>
													<span class="label-product label-new"><?php echo __('New'); ?></span>
											<?php }
											} ?>
										</div>
									<!--- End -->
									<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
										<?php $productImageThumb = $block->getImage($_product, 'category_page_grid-1');?>
										<span class="image0 image-switch">
											<?php echo $productImage->toHtml(); ?>
										</span>
										<span class="image1 image-switch">
											<?php echo $productImageThumb->toHtml(); ?>
										</span>
									</a>
									<?php if( $this->getConfigSys('addtowishlist') || $this->getConfigSys('addtocompare') || $this->getConfigSys('addtocart') ){?>
										<ul class="add-to-links">
										<?php if ($this->getConfigSys('addtocart')) { ?>
											<li>
												<div class="actions-primary">
													<?php if ($_product->isSaleable()): ?>
														<?php $postParams = $block->getAddToCartPostParams($_product); ?>
														<form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $block->getAddToCartUrl($_product); ?>" method="post">
															<input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
															<input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
															<?php echo $block->getBlockHtml('formkey')?>
															<button class="btn btn-add-to-cart" type="submit"
																	title="<?php echo $block->escapeHtml(__('test66')); ?>" >
																<span><?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('your_cart')->toHtml();?></span>
															</button>
														</form>
													<?php else: ?>
														<?php if ($_product->getIsSalable()): ?>
															<button class="btn btn-add-to-cart"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></button>
														<?php else: ?>
															<button class="btn btn-add-to-cart"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></button>
														<?php endif; ?>
													<?php endif; ?>
												</div>
											</li>
										<?php }?>
										<?php if( $this->getConfigSys('addtowishlist')): ?>
												<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
												<li>
													<a href="#"
													   class="action wishlist"
													   title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
													   aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
													   data-post='<?php  echo $block->getAddToWishlistParams($_product); ?>'
													   data-action="add-to-wishlist"
													   role="button">
														<i class="fa fa-heart" aria-hidden="true"></i>
													</a>
												</li>
												<?php endif; ?>
											<?php endif; ?>
					
										<?php if( $this->getConfigSys('addtocompare')): ?>
											<?php
											$compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
											?>
											<li><a href="#"
											   class="action compare"
											   title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
											   aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
											   data-post='<?php  echo $compareHelper->getPostDataParams($_product); ?>'
											   role="button">
												<i class="fa fa-exchange" aria-hidden="true"></i>
												</a>
											</li>
										<?php endif; ?>
										<li>
											<div class="quickview-product">
												<a  data-role="quickview-button" data-id="<?php echo $_product->getId(); ?>" href="<?php echo $block->getUrl('quickview/product/quickview/id/' . $_product->getId()) ?>" title="<?php echo ('TEST123') ?>" class="ajax diamond tooltip-hover" data-placement="top"><i class="fa fa-search" aria-hidden="true"></i></a>
											</div>
										</li>
										</ul>
									<?php }?>
								</div>
								<div class="product-info">
										<?php
											$_productNameStripped = $block->stripTags($_product->getName(), null, true);
										?>
										<h3 class="product-name">
											<a href="<?php echo $_product->getProductUrl() ?>">
												<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
											</a>
										</h3>
										<div class="box-rate-price clearfix">
											<?php if( $this->getConfigSys('show_price') ): ?>
												 <?php echo $block->getProductPrice($_product) ?>
											<?php endif; ?>
											<?php if($this->getConfigSys('review')): ?>
											<div class="product-ratting">	
												<?php echo $block->getReviewsSummaryHtml($_product, $templateType,true); ?>
											</div>
											<?php endif; ?>
										</div>		
								</div>
							<?php $i++;?>
						</div>
						<?php if($i %$rows == 0) echo "</div>"; ?>                  
					<?php endforeach; ?>
						<?php if($i %$rows != 0) echo "</div>"; ?>                
				</div>
			</div>
		<?php if (!$block->isRedirectToCartEnabled()) : ?>
			<script type="text/x-magento-init">
			{
				"[data-role=tocart-form], .form.map.checkout": {
					"catalogAddToCart": {}
				}
			}
			</script>
		<?php endif; ?>
			<script>
				require([
					'jquery',
					'mage/mage',
					'themevast/owl'
				], function ($) {
					'use strict';
				jQuery(document).ready(function ($) {
					(function (element) {
							var $element = $(element);
							setTimeout(function () {
								$('.deal_preload', $element).remove();
								hotDealSlider($element);

							}, 500);
						   function hotDealSlider($element){
							var hotDeal = $(".hotdeal .owl",$element);
							hotDeal.owlCarousel({
									autoPlay : <?php if($this->getConfigSys('auto')) echo 'true'; else echo 'false'; ?>,
									items : <?php if($this->getConfigSys('itemsDefault')) echo $this->getConfigSys('itemsDefault'); else echo '4'; ?>,
									itemsDesktop : [1199,<?php echo $this->getConfigSys('itemsDefault'); ?>],
									itemsDesktopSmall : [980,<?php echo $this->getConfigSys('itemsDesktopSmall'); ?>],
									itemsTablet: [768,<?php echo $this->getConfigSys('itemsTablet'); ?>],
									itemsMobile : [479,<?php echo $this->getConfigSys('itemsMobile'); ?>],
									slideSpeed : <?php if($this->getConfigSys('speed')) echo $this->getConfigSys('speed'); else echo '500'; ?>,
									navigation : <?php if($this->getConfigSys('next_back')) echo 'true'; else echo 'false'; ?>,
									stopOnHover : true,
									margin:30,
									pagination :<?php if($this->getConfigSys('nav_ctrl')) echo 'true'; else echo 'false'; ?>,
									/* scrollPerPage:true, */
								});
						   }
							})('#<?php echo $idDeal ?>');
				});
			});
			</script>
	<?php endif; ?>
	</div>
</div>
<?php } ?>