<?php 
use Magento\Framework\App\Action\Action;
if($this->getConfig('enabled')){ // start enable module?>
	<?php $_productCollection = $this->getProducts();
$_helper = $this->helper('Magento\Catalog\Helper\Output');

$_helperData = $this->helper('Themevast\PriceCountdown\Helper\Data');
$timer_active = $_helperData->getConfigData('pricecountdown/general/activate_pricecountdown');
$timer_head_active = $_helperData->getConfigData('pricecountdown/general/activate_themevast_heading');
$timer_desc_active = $_helperData->getConfigData('pricecountdown/general/activate_themevast_description');
$timer_color = $_helperData->getConfigData('pricecountdown/pricecountdown_color/text');
$desc_color = $_helperData->getConfigData('pricecountdown/pricecountdown_color/description');
$head_color = $_helperData->getConfigData('pricecountdown/pricecountdown_color/heading_text_color');
$timer_head = $_helperData->getConfigData('pricecountdown/general/heading');
$count = 1;
$_current_timer = time();

	?>
	<div class="pricecountdown-product">
		<?php			
			if ($block->getMode() == 'grid') {
				$viewMode = 'grid';
				$image = 'category_page_grid';
				$showDescription = false;
				$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
			} else {
				$viewMode = 'list';
				$image = 'category_page_list';
				$showDescription = true;
				$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
			}
			$pos = $block->getPositioned();
			
		?>
		<?php if($this->getConfig('title')){?>
			<div class="title-product-heading countdown-heading">
				<h2 class="product-title"><?php echo $this->getConfig('title')?></h2>
			</div>
		<?php }?>
		<?php if(!$_productCollection->getSize()): ?> 
			<div class="message info empty">	
				<p class="note-msg"><?php echo __('There are no products matching the selection.') ?></p>
			</div>
		<?php else: ?>
			<?php
			if(!$rows = $this->getConfig('items'))
				$rows = 1;
			?>	
			<div class="product-grid">
				<div class="owl">
					<?php $_collectionSize = $_productCollection->count() ?>
					<?php $i=0; foreach ($_productCollection as $_product): ?>
						<?php if($i %$rows == 0) echo "<div class='item countdown-item'>"; ?>
						<div class="product-item">
								<?php
								$productImage = $block->getImage($_product, $image);
								if ($pos != null) {
									$position = ' style="left:' . $productImage->getWidth() . 'px;'
										. 'top:' . $productImage->getHeight() . 'px;"';
								}
								?>
								<?php // Product Image ?>
								<div class="product-photo">
									<div class="new-sale-label">
								        <?php
								         $specialprice = $_product->getSpecialPrice();
								         $specialPriceFromDate = $_product->getSpecialFromDate();
								         $specialPriceToDate = $_product->getSpecialToDate();
								         $_price=$_product->getPrice();
								         $_finalPrice=$_product->getFinalPrice();
								         $today = time();?>
								
								         <?php 
								         if ($specialprice) {
								          if ($today >= strtotime($specialPriceFromDate) && $today <= strtotime($specialPriceToDate) || $today >= strtotime($specialPriceFromDate) && is_null($specialPriceToDate)) { ?>
								           <span class="label-product label-sale">
								           		<?php if($_finalPrice < $_price): ?>
										          <?php $_savePercent = 100 - round(($_finalPrice / $_price)*100); ?>
										            <?php echo __('-%1',$_savePercent."%");?>
										          <?php endif; ?>
								           </span>
								          <?php }
								         }
								         ?>
								         <?php
								         $now = date("Y-m-d");
								         $newsFrom = substr($_product->getNewsFromDate(), 0, 10);
								         $newsTo = substr($_product->getNewsToDate(), 0, 10);

								         if (($newsTo != '' || $newsFrom != '') && !$specialprice) {
								         if (($newsTo != '' && $newsFrom != '' && $now >= $newsFrom && $now <= $newsTo) || ($newsTo == '' && $now >= $newsFrom) || ($newsFrom == '' && $now <= $newsTo)) {?>
								           <span class="label-product label-new"><?php echo __('New'); ?></span>
								         <?php }
								         } ?>
								       </div>
									<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
										<?php $productImageThumb = $block->getImage($_product, 'category_page_grid-1');?>
										<span class="image0 image-switch">
											<?php echo $productImage->toHtml(); ?>
										</span>
										<span class="image1 image-switch">
											<?php echo $productImageThumb->toHtml(); ?>
										</span>
									</a>
									<div class="quickview-product">
		                                <a  data-role="quickview-button" data-id="<?php echo $_product->getId(); ?>" href="<?php echo $block->getUrl('quickview/product/quickview/id/' . $_product->getId()) ?>" title="" class="ajax diamond tooltip-toggle" data-placement="top" data-original-title="<?php echo ('Quick view') ?>">
		                                <?php echo $block->escapeHtml(__('Quick View')); ?>
		                                </a>
		                            </div>
									
								</div>
								<div class="product-info clearfix">
									<?php
										$_productNameStripped = $block->stripTags($_product->getName(), null, true);
									?>
									<h3 class="product-name">
										<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
											<?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
										</a>
									</h3>
									<?php if($this->getConfig('review')): ?>
										<div class="product-ratting">
											<?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
										</div>
									<?php endif; ?>
									<?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
									<div class="count-down clearfix">
										<?php if($timer_active == 1){ ?>
										<?php $_product = $_product->load($_product->getId()) ?>
										<?php $toDate = $_product->getSpecialTODate();?>
										<?php $fromDate = $_product->getSpecialFromDate(); ?>
										<?php if(($_product->getPrice() > $_product->getSpecialPrice() || $_product->getTypeId() == 'bundle') && $_product->getTimershow() == 1) { ?>
											<?php if($_product->getSpecialPrice()!= 0 || $_product->getSpecialPrice()!= "" ) { ?>
													<?php if($timer_head_active == 'showall' || $timer_head_active == 'listpage' && $timer_head_active!='hideall' && $timer_head!= '') { ?>
													<div id="heading<?php echo $count; ?>" style="color:#<?php echo $head_color; ?>; font-size: 14px; font-weight:bold;padding-top:0px;clear: both;"><?php echo $timer_head ?></div>
													<?php } ?>
													<div id="countbox_<?php echo $count; ?>" class="timer-list"></div>
													<?php if($timer_desc_active == 'showall' || $timer_desc_active == 'listpage' && $timer_desc_active!='hideall') { ?>
													<?php
															if($_product->getTypeId() == 'bundle')
															{
																echo '<h1>Discount up to '.(100 - $_product->getSpecialPrice()*1).'% </h1>';
															}
														} ?> 
													<script type="text/javascript">
													var DisplayFormat = "<span class='countdown-section'><span class='countdown-amount'>%%D%%</span><span class='countdown-period'><?php echo __('Days') ?></span></span><span class='countdown-section'><span class='countdown-amount'>%%H%%</span><span class='countdown-period'><?php echo __('Hours') ?></span></span><span class='countdown-section'><span class='countdown-amount'>%%M%%</span><span class='countdown-period'><?php echo __('Mins') ?></span></span><span class='countdown-section'><span class='countdown-amount'>%%S%%</span><span class='countdown-period'><?php echo __('Secs') ?></span></span>";
														var dthen<?php echo $count; ?> = new Date("<?php echo Date("m/d/y", strtotime($toDate)).' 11:59:00 PM'; ?>");
														start = "<?php echo Date("m/d/y h:i:s A", $_current_timer); ?>";
														start_date = Date.parse(start);
														var dnow<?php echo $count; ?> = new Date(start_date);
														if(CountStepper>0)
															ddiff= new Date((dnow<?php echo $count; ?>)-(dthen<?php echo $count; ?>));
														else
															ddiff = new Date((dthen<?php echo $count; ?>)-(dnow<?php echo $count; ?>));
														//gsecs<?php echo $count; ?> = Math.floor(ddiff.valueOf()/1000);
														<?php if(strtotime($fromDate) <= $_current_timer){ ?>
															gsecs<?php echo $count; ?> = Math.floor(ddiff.valueOf()/1000);
														<?php }else{ ?>
															gsecs<?php echo $count; ?> = -1;
														<?php } ?>

														var iid<?php echo $count; ?> = "countbox_<?php echo $count; ?>";
														CountBack(gsecs<?php echo $count; ?>,"countbox_"+j, j);
														j++;
													</script>
													<?php $count = $count + 1; ?>
													<?php
												}
											}
										} ?>
									</div>
									<div class="actions-primary">
										<?php if ($_product->isSaleable()): ?>
											<?php $postParams = $block->getAddToCartPostParams($_product); ?>
											<form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
												<input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
												<input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
												<?php echo $block->getBlockHtml('formkey')?>
												<button type="submit" title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>" class="btn btn-add-to-cart">
													<span><?php echo $block->escapeHtml(__('Add to Cart')); ?></span>
												</button>
											</form>
										<?php else: ?>
											<?php if ($_product->getIsSalable()): ?>
												<button class="btn btn-add-to-cart"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></button>
											<?php else: ?>
												<button class="btn btn-add-to-cart"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></button>
											<?php endif; ?>
										<?php endif; ?>
									</div>
								</div>
							<?php $i++;?>
						</div>
						<?php if($i %$rows == 0) echo "</div>"; ?>                  
					<?php endforeach; ?>
						<?php if($i %$rows != 0) echo "</div>"; ?>                
				</div>
			</div>
		<?php if (!$block->isRedirectToCartEnabled()) : ?>
			<script type="text/x-magento-init">
			{
				"[data-role=tocart-form], .form.map.checkout": {
					"catalogAddToCart": {}
				}
			}
			</script>
		<?php endif; ?>
			<script type="text/javascript">
				require([
					'jquery',
					'mage/mage',
					'themevast/owl'
				], function ($) {
					'use strict';

					jQuery(".pricecountdown-product .owl-carousel").owlCarousel({
						autoplay :false,
						items : 1,
						smartSpeed : 500,
						dotsSpeed : 500,
						rewindSpeed : 500,
						nav : false,
						autoplayHoverPause : true,
						dots : false,
						scrollPerPage:true,
						margin: 0,
						responsive: {
						0: {
							items: 1,
						},
						480: {
							items:1,
						},
						768: {
							items:1,
						},
						991: {
							items:1,
						},						
						1200: {
							items:1,
						}
					 }
					});
				});
			</script>
	<?php endif; ?>
	</div>
<?php } ?>