<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile
if (file_exists("conf/conf.php"))
    @include 'conf/conf.php';

$conn = new mysqli($conf->db->host, $conf->db->user, $conf->db->pass, $conf->db->name);

/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
$sellerGroupId = $customerId = $customerGroupId = $status = '';
$urlInterface = \Magento\Framework\App\ObjectManager::getInstance()->get('Magento\Framework\UrlInterface');
$currentUrl = $urlInterface->getCurrentUrl();
$helper = $this->helper('Apptha\Marketplace\Helper\Objectmanager');
$customerSession = $helper->customerSession();
$customerDatas = $customerSession->getCustomer();
if ($customerSession->isLoggedIn()) {
    $customerId = $customerSession->getId();
    $customerGroupId = $customerDatas->getGroupId();
    $helper = $this->helper('Apptha\Marketplace\Helper\Objectmanager');
    $sellerGroupData = $helper->customerSessionGroup($customerGroupId);
    $sellerGroupId = $sellerGroupData->getId();
    $status = $helper->sellerStatus($customerId);
}

$remote_ip = $_SERVER['REMOTE_ADDR'];
$remote_ip = "'$remote_ip'";

$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$date = date("Y-m-d");

if($customerId != '') {
    $query = "SELECT wishlist_id ";
    $query .= "FROM mgkf_wishlist ";
    $query .= "WHERE customer_id = '".$customerId."'";
    $result = $conn->query($query);
    $row = $result->fetch_assoc();
    $wishlistId = $row['wishlist_id'];

    $query = "SELECT product_id ";
    $query .= "FROM mgkf_wishlist_item ";
    $query .= "WHERE wishlist_id = '".$wishlistId."'";
    $result = $conn->query($query);
    $wishlistArr = array();
    while($row = $result->fetch_assoc()) {
        $wishlistProductId = $row['product_id'];
        array_push($wishlistArr, $wishlistProductId);
    }
    $wishlistList = implode(",", $wishlistArr);
    ?>
    <div id="wishlist_items_user" class="d-none">
        <?php echo $wishlistList; ?>
    </div>
    <script>
    var interval = setInterval(myTimer, 1000);
    function myTimer() {
        var user_id = "<?php echo $customerId; ?>";
        jQuery("#wishlist_items_user").load("/wishlistAdd.php", {user_id:user_id});
    }
    </script>
<?php 
}
else {
    $query = "SELECT id ";
    $query .= "FROM mgkf_guest_wishlist ";
    $query .= "WHERE remote_ip = '".$remote_ip."'";
    $result = $conn->query($query);
    if($result) {
        $row = $result->fetch_assoc();
        $guestWishlistId = $row['id'];

        $query = "SELECT product_id ";
        $query .= "FROM mgkf_guest_wishlist_item ";
        $query .= "WHERE guest_wishlist_id = '".$guestWishlistId."'";
        $result = $conn->query($query);
        $guestWishlistArr = array();
        while($row = $result->fetch_assoc()) {
            $guestWishlistProductId = $row['product_id'];
            array_push($guestWishlistArr, $guestWishlistProductId);
        }
        $guestWishlistList = implode(",", $guestWishlistArr);
        ?>
        <div id="wishlist_items_guest" class="d-none">
            <?php echo $guestWishlistList; ?>
        </div>
        <script>
        var interval = setInterval(myTimer, 1000);
        function myTimer() {
            var guest_id = "<?php echo $remote_ip; ?>";
            jQuery("#wishlist_items_guest").load("/wishlistAdd.php", {guest_id:guest_id});
        }
        </script>
<?php
    }
}
?>
<?php if (!$_productCollection->count()) { ?>
    <div class="message info empty">
        <div>
            <?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?>
        </div>
    </div>
<?php } else { ?>
  <div class="row mt-3">
  <div class="col-12 col-md-12">
  <div class="categories-page">
        <div class="top-toolbar pt-md-1">
            <?php echo $block->getToolbarHtml() ?>
        </div>
        <?php echo $block->getAdditionalHtml() ?>
        <?php
        if ($block->getMode() == 'grid') {
            $viewMode = 'grid';
            $image = 'category_page_grid';
            $showDescription = false;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
        } else {
            $viewMode = 'list';
            $image = 'category_page_list';
            $showDescription = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
        }
        /*Grid*/
        if ($viewMode == "grid") {
            /**
             * Position for actions regarding image size changing in vde if needed
             */
            $pos = $block->getPositioned();
        ?>
            <div class="<?php /* @escapeNotVerified */ echo $viewMode; ?> product-<?php /* @escapeNotVerified */ echo $viewMode; ?>">
                <?php $iterator = 1; ?>
                <ol class="pl-0 pl-md-3 row">
                    <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
                    <?php
                    $i = 0;
                    foreach ($_productCollection as $_product) {
                        $_productId = $_product->getId();
                    ?>
                        <?php /* @escapeNotVerified */ echo ($iterator++ == 1) ? '<li class="col-6 col-lg-6 col-xl-4 col-xxl-3 g-2 g-md-3 mb-0">' : '</li><li class="col-6 col-lg-6 col-xl-4 col-xxl-3 g-2 g-md-3 mb-0">' ?>
                        <div class="card product-card border-0 shadow">
                            <?php
                            $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                            $storeManager = $objectManager->create('Magento\Store\Model\StoreManagerInterface');
                            $rootId = $storeManager->getStore()->getRootCategoryId();
                            $categoryCollection = $_product->getCategoryCollection()->addAttributeToSelect('name')
                                ->addAttributeToSelect('is_active')
                                ->addAttributeToFilter('entity_id', ['neq' => $rootId])
                                ->addUrlRewriteToResult()
                                ->getFirstItem();
                            ?>
                            <?php
                            $productImage = $block->getImage($_product, $image);
                            if ($pos != null) {
                                $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                    . 'top:' . $productImage->getHeight() . 'px;"';
                            }
                            ?>
                            <?php // Product Image 
                            ?>
                            <div class="product-photo">
                                <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                                    <?php $productImageThumb = $block->getImage($_product, 'category_page_grid-1'); ?>
                                    <span class="image0 image-switch">
                                        <?php echo $productImage->toHtml(); ?>
                                    </span>
                                </a>
                            </div>
                            <div class="card-body">
                                <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
                                <?php
                                $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                                $_productName = $_helper->productAttribute($_product, $_product->getName(), 'name');
                                $query_brand_id = "SELECT DISTINCT(mgkf_catalog_product_entity_int.value), mgkf_catalogsearch_fulltext_scope1.data_index as product_name ";
                                $query_brand_id .= "FROM mgkf_catalog_product_entity_int, mgkf_catalogsearch_fulltext_scope1 ";
                                $query_brand_id .= "WHERE mgkf_catalog_product_entity_int.entity_id = mgkf_catalogsearch_fulltext_scope1.entity_id ";
                                $query_brand_id .= "AND mgkf_catalog_product_entity_int.attribute_id = 197 ";
                                $query_brand_id .= "AND mgkf_catalogsearch_fulltext_scope1.attribute_id = 74 ";
                                $query_brand_id .= "AND mgkf_catalogsearch_fulltext_scope1.data_index = '" . $_productName . "'";
                                $result_brand_id = $conn->query($query_brand_id);
                                $row_brand_id = $result_brand_id->fetch_assoc();
                                $value = $row_brand_id['value'];
                                $query_brand = "SELECT value FROM mgkf_eav_attribute_option_value ";
                                $query_brand .= "WHERE option_id = '" . $value . "'";
                                $result_brand = $conn->query($query_brand);
                                $row_brand = $result_brand->fetch_assoc();
                                $_brandName = $row_brand['value'];

                                $query_seller = "SELECT value FROM mgkf_catalog_product_entity_int ";
                                $query_seller .= "WHERE attribute_id = 158 ";
                                $query_seller .= "AND entity_id = '".$_productId."'";
                                $result_seller = $conn->query($query_seller);
                                $row_seller = $result_seller->fetch_assoc();
                                $sellerId = $row_seller['value'];

                                $query_category = "SELECT mgkf_catalog_category_entity_varchar.entity_id, mgkf_catalog_category_entity_varchar.value ";
                                $query_category .= "FROM mgkf_catalog_category_entity_varchar, mgkf_catalog_category_product ";
                                $query_category .= "WHERE mgkf_catalog_category_entity_varchar.entity_id = mgkf_catalog_category_product.category_id ";
                                $query_category .= "AND mgkf_catalog_category_entity_varchar.store_id = 0 ";
                                $query_category .= "AND mgkf_catalog_category_entity_varchar.attribute_id = 45 ";
                                $query_category .= "AND mgkf_catalog_category_product.product_id = '".$_productId."' ";
                                $query_category .= "LIMIT 0,1";
                                $result_category = $conn->query($query_category);
                                $row_category = $result_category->fetch_assoc();
                                $categoryId = $row_category['entity_id'];
                                $categoryName = $row_category['value'];

                                $query_subcategory = "SELECT mgkf_catalog_category_entity_varchar.entity_id, mgkf_catalog_category_entity_varchar.value ";
                                $query_subcategory .= "FROM mgkf_catalog_category_entity_varchar, mgkf_catalog_category_product ";
                                $query_subcategory .= "WHERE mgkf_catalog_category_entity_varchar.entity_id = mgkf_catalog_category_product.category_id ";
                                $query_subcategory .= "AND mgkf_catalog_category_entity_varchar.store_id = 0 ";
                                $query_subcategory .= "AND mgkf_catalog_category_entity_varchar.attribute_id = 45 ";
                                $query_subcategory .= "AND mgkf_catalog_category_product.product_id = '".$_productId."' ";
                                $query_subcategory .= "LIMIT 1,1";
                                $result_subcategory = $conn->query($query_subcategory);
                                $row_subcategory = $result_subcategory->fetch_assoc();
                                $subcategoryId = $row_subcategory['entity_id'];
                                $subcategoryName = $row_subcategory['value'];

                                $query_price = "SELECT DISTINCT(max_price) FROM mgkf_catalog_product_index_price ";
                                $query_price .= "WHERE entity_id = '".$_productId."'";
                                $result_price = $conn->query($query_price);
                                $row_price = $result_price->fetch_assoc();
                                $productPrice = (float)number_format($row_price['max_price'] * 4.726883, 2, ',', '');

                                $query_category_discount = "SELECT category_id, subcategory_name, discount_type ";
                                $query_category_discount .= "FROM mgkf_marketplace_discount_category ";
                                $query_category_discount .= "WHERE category_id = '".$categoryId."' ";
                                $query_category_discount .= "AND subcategory_name = '".$subcategoryName."' ";
                                $query_category_discount .= "AND seller_id = '".$sellerId."' ";
                                $query_category_discount .= "AND is_active = 1 ";
                                $query_category_discount .= "AND date_from <= '".$date."' ";
                                $query_category_discount .= "AND date_to >= '".$date."'";
                                $result_category_discount = $conn->query($query_category_discount);
                                if($result_category_discount) {
                                $countCategoryDiscount = $result_category_discount->num_rows;
                                    if($countCategoryDiscount > 0) {
                                        $row_category_discount = $result_category_discount->fetch_assoc();
                                        $discountCategory = str_replace("%", "", $row_category_discount['discount_type']);
                                    }
                                }

                                $query_product_discount = "SELECT * FROM mgkf_marketplace_discount_products ";
                                $query_product_discount .= "WHERE is_active = 1 ";
                                $query_product_discount .= "AND seller_id = '".$sellerId."' ";
                                $query_product_discount .= "AND product_id = '".$_productId."' ";
                                $query_product_discount .= "AND date_from <= '".$date."' ";
                                $query_product_discount .= "AND date_to >= '".$date."'";
                                $result_product_discount = $conn->query($query_product_discount);
                                if($result_product_discount) {
                                $countProductDiscount = $result_product_discount->num_rows;
                                    if($countProductDiscount > 0) {
                                        $row_product_discount = $result_product_discount->fetch_assoc();
                                        $discount = str_replace("%", "", $row_product_discount['discount']);
                                        $discountProduct = $discount;
                                        $discountFrom = $row_product_discount['date_from'];
                                        $discountTo = $row_product_discount['date_to'];
                                    }
                                }

                                if($result_category_discount) {
                                    if($countCategoryDiscount > 0) {
                                        $discount = $discountCategory;
                                        $newPrice = number_format(($productPrice - ($productPrice * ($discountCategory / 100))), 2, ',', '.');
                                    }
                                }
                                if($result_product_discount) {
                                    if($countProductDiscount > 0) {
                                        $discount = $discountProduct;
                                        $newPrice = number_format(($productPrice - ($productPrice * ($discountProduct / 100))), 2, ',', '.');
                                    }
                                }
                                if($result_category_discount && $result_product_discount) {
                                    if($countCategoryDiscount > 0 && $countProductDiscount > 0) {
                                        if($discountCategory >= $discountProduct) {
                                            $discount = $discountCategory;
                                            $newPrice = number_format(($productPrice - ($productPrice * ($discountCategory / 100))), 2, ',', '.');
                                        }
                                        else {
                                            $discount = $discountProduct;
                                            $newPrice = number_format(($productPrice - ($productPrice * ($discountProduct / 100))), 2, ',', '.');
                                        }
                                    }
                                }
                                ?>
                                <div class="product-name">
                                    <?php if ($_brandName != '') { ?>
                                        <p class="text-center mb-1">
                                            <b><?php echo $_brandName; ?></b>
                                        </p>
                                        <p class="description-product">
                                            <?php echo /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                                        </p>                                        
                                    <?php
                                    } else { ?>
                                        <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
                                            <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                                        </a>
                                    <?php
                                    }
                                    ?>
                                </div>
                                <div class="price-info d-flex">
                                    <div id="product-price-<?php echo $i; ?>">
                                        <?php /* @escapeNotVerified */ echo $block->getProductPrice($_product); ?>
                                    </div>
                                    <?php
                                    if($result_category_discount || $result_product_discount) {
                                        if($countProductDiscount > 0 || $countCategoryDiscount > 0) {
                                    ?>
                                            &nbsp;
                                            <input type="hidden" id="discount-<?php echo $i; ?>" /> 
                                            <script>
                                                var parent = document.getElementById("layer-product-list");
                                                var nodesSameClass = parent.getElementsByClassName("card-body");
                                                for(var i=0; i<nodesSameClass.length; i++) {
                                                    if(document.getElementById("discount-"+i)) {
                                                        if(document.getElementById("product-price-"+i)) {
                                                            document.getElementById("product-price-"+i).setAttribute("style", "text-decoration:line-through !important;")   
                                                        }
                                                    }
                                                }
                                            </script>
                                            <div id="new-price-<?php echo $i; ?>">
                                                <div class="price-box price-final_price" data-role="priceBox">
                                                    <span class="normal-price">
                                                        <span class="price-container price-final_price tax weee">
                                                            <span data-price-type="finalPrice" class="price-wrapper ">
                                                                <span class="price-discount font-17 text-red"><?php echo $newPrice . ' Ron'; ?></span>
                                                            </span>
                                                        </span>
                                                    </span>
                                                </div>
                                            </div>
                                            <div class="discount">
                                                <?php echo '-' . $discount . '%'; ?>
                                            </div>
                                        <?php
                                        }
                                    }
                                    ?>
                                </div>
                                <div class="d-md-none card-actions">
                                    <ul class="align-items-center d-flex justify-content-around">
                                        <?php 
                                        if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()) { 
                                        ?>
                                            <li class="wishlist m-0 p-2">
                                                <?php 
                                                if($customerId != '') {
                                                    if(strpos($wishlistList, $_productId) !== false) {
                                                    ?>
                                                        <a data-toggle="tooltip" title="<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('product_is_in_wishlist')->toHtml(); ?>" aria-label="<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('product_is_in_wishlist')->toHtml(); ?>" role="button">
                                                            <i class="fas fa-heart"></i>
                                                        </a>
                                                    <?php
                                                    }
                                                    else { 
                                                    ?>
                                                        <a id="add-to-wishlist-btn-<?php echo $_productId; ?>" onclick="add_to_wishlist(<?php echo $customerId . ',' . $_productId ?>);" data-toggle="tooltip" title="<?php echo $block->escapeHtml(__('Add to Wishlist')); ?>" aria-label="<?php echo $block->escapeHtml(__('Add to Wishlist')); ?>" role="button">
                                                            <i class="fal fa-heart" id="heart-<?php echo $_productId; ?>"></i>
                                                        </a>
                                                    <?php
                                                    }
                                                }
                                                else {
                                                    if($result) {
                                                        if(strpos($guestWishlistList, $_productId) !== false) {
                                                        ?>
                                                            <a data-toggle="tooltip" title="<?php echo $block->escapeHtml(__('Add to Wishlist')); ?>" aria-label="<?php echo $block->escapeHtml(__('Add to Wishlist')); ?>" role="button">
                                                                <i class="fas fa-heart"></i>
                                                            </a>
                                                        <?php
                                                        }
                                                        else {
                                                        ?>
                                                            <a id="add-to-wishlist-btn-<?php echo $_productId; ?>" onclick="add_to_wishlist(<?php echo $remote_ip . ',' . $_productId ?>);" data-toggle="tooltip" title="<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('product_is_in_wishlist')->toHtml(); ?>" aria-label="<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('product_is_in_wishlist')->toHtml(); ?>" role="button">
                                                                <i class="fal fa-heart" id="heart-<?php echo $_productId; ?>"></i>
                                                            </a>
                                                        <?php
                                                        }
                                                    }
                                                    else {
                                                    ?>
                                                        <a data-toggle="tooltip" title="<?php echo $block->escapeHtml(__('Add to Wishlist')); ?>" aria-label="<?php echo $block->escapeHtml(__('Add to Wishlist')); ?>" role="button">
                                                            <i class="fal fa-heart"></i>
                                                        </a>
                                                    <?php
                                                    }
                                                }
                                                ?>
                                            </li>
                                        <?php 
                                        }
                                        $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
                                        ?>
                                    </ul>
                                </div>
                                </a>
                            </div>
                            <?php echo ($iterator == count($_productCollection) + 1) ? '</li>' : '' ?>
                    <?php 
                        $i++;
                    } 
                    ?>
                </ol>
            </div>
            <script>
                var parent = document.getElementById("layer-product-list");
                var price = parent.getElementsByClassName("price");
                for(var i=0; i<price.length; i++) {
                    if(document.getElementById("new-price-"+i)) {
                        price[i].setAttribute("id", "old-price-"+i);
                        var old_price = document.getElementById("old-price-"+i).innerText;
                        var old_price_format = old_price.replace(/[^.,\d]/g, '');
                        document.getElementById("old-price-"+i).innerText = old_price_format;
                    }
                }
            </script>
            <?php if (!$block->isRedirectToCartEnabled()) { ?>
                <script type="text/x-magento-init">
                    {
                "[data-role=tocart-form], .form.map.checkout": {
                    "catalogAddToCart": {}
                }
            }
            </script>
            <?php } ?>
        <?php
            /*List*/
        } else {
            /**
             * Position for actions regarding image size changing in vde if needed
             */
            $pos = $block->getPositioned();
        ?>
            <div class="<?php /* @escapeNotVerified */ echo $viewMode; ?> product-<?php /* @escapeNotVerified */ echo $viewMode; ?>">
                <?php $iterator = 1; ?>
                <ol class="products list items product-items">
                    <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
                    <?php foreach ($_productCollection as $_product) { ?>
                        <?php /* @escapeNotVerified */ echo ($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                        <div class="product-info-list product-list-item product-item-info" data-container="product-list">
                            <div class="item-inner">
                                <div class="row">
                                    <?php
                                    $productImage = $block->getImage($_product, $image);
                                    if ($pos != null) {
                                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                            . 'top:' . $productImage->getHeight() . 'px;"';
                                    }
                                    ?>
                                    <?php // Product Image 
                                    ?>
                                    <div class="col-sm-5 col-md-3 col-xs-5">
                                        <div class="product-photo">
                                            <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product-image product photo product-item-photo" tabindex="-1">
                                                <?php $productImageThumb = $block->getImage($_product, 'category_page_grid-1'); ?>
                                                <span class="image0 image-switch">
                                                    <?php echo $productImage->toHtml(); ?>
                                                </span>
                                                <span class="image1 image-switch">
                                                    <?php echo $productImageThumb->toHtml(); ?>
                                                </span>
                                            </a>
                                            <div class="new-sale-label">
                                                <?php
                                                $specialprice = $_product->getSpecialPrice();
                                                $specialPriceFromDate = $_product->getSpecialFromDate();
                                                $specialPriceToDate = $_product->getSpecialToDate();
                                                $_price = $_product->getPrice();
                                                $_finalPrice = $_product->getFinalPrice();
                                                $today = time();
                                                ?>
                                                <?php
                                                if ($specialprice) {
                                                    if ($today >= strtotime($specialPriceFromDate) && $today <= strtotime($specialPriceToDate) || $today >= strtotime($specialPriceFromDate) && is_null($specialPriceToDate)) { ?>
                                                        <span class="label-product label-sale">
                                                            <?php if ($_finalPrice < $_price) { ?>
                                                                <?php $_savePercent = 100 - round(($_finalPrice / $_price) * 100); ?>
                                                                <?php echo __('-%1', $_savePercent . "%"); ?>
                                                            <?php } ?>
                                                        </span>
                                                <?php }
                                                }
                                                ?>
                                                <?php
                                                $now = date("Y-m-d");
                                                $newsFrom = substr($_product->getNewsFromDate(), 0, 10);
                                                $newsTo = substr($_product->getNewsToDate(), 0, 10);

                                                if (($newsTo != '' || $newsFrom != '') && !$specialprice) {
                                                    if (($newsTo != '' && $newsFrom != '' && $now >= $newsFrom && $now <= $newsTo) || ($newsTo == '' && $now >= $newsFrom) || ($newsFrom == '' && $now <= $newsTo)) { ?>
                                                        <span class="label-product label-new">
                                                            <?php echo __('New'); ?>
                                                        </span>
                                                <?php }
                                                } ?>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-6 col-sm-7 col-xs-7">
                                        <div class="product-list-details product-info product details product-item-details">
                                            <?php
                                            $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                                            $storeManager = $objectManager->create('Magento\Store\Model\StoreManagerInterface');
                                            $rootId = $storeManager->getStore()->getRootCategoryId();
                                            $categoryCollection = $_product->getCategoryCollection()->addAttributeToSelect('name')
                                                ->addAttributeToSelect('is_active')
                                                ->addAttributeToFilter('entity_id', ['neq' => $rootId])
                                                ->addUrlRewriteToResult()
                                                ->getFirstItem();
                                            ?>
                                            <?php
                                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                                            ?>
                                            <h3 class="product-name">
                                                <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
                                                    <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                                                </a>
                                            </h3>
                                            <?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
                                            <?php if ($showDescription) { ?>
                                                <div class="product description product-item-description">
                                                    <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                                </div>
                                            <?php } ?>
                                        </div>
                                    </div>
                                    <div class="col-sm-3">
                                        <div class="product-list-details product-info product details product-item-details">
                                            <?php if ($block->displayProductStockStatus()) { ?>
                                                <?php if ($_product->isAvailable()) { ?>
                                                    <div class="stock available" title="<?php /* @escapeNotVerified */ echo __('Availability') ?>">
                                                        <?php /* @escapeNotVerified */ echo __('Availability: ') ?><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span>
                                                    </div>
                                                <?php } else { ?>
                                                    <div class="stock unavailable" title="<?php /* @escapeNotVerified */ echo __('Availability') ?>">
                                                        <?php /* @escapeNotVerified */ echo __('Availability: ') ?><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span>
                                                    </div>
                                                <?php } ?>
                                            <?php } ?>
                                            <?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
                                            <?php echo $block->getProductDetailsHtml($_product); ?>

                                        </div>
                                    </div>
                                </div>
                            </div>
                            <?php echo ($iterator == count($_productCollection) + 1) ? '</li>' : '' ?>
                        <?php } ?>
                </ol>
            </div>
            <div class="bottom-toolbar">
                <?php echo $block->getToolbarHtml() ?>
            </div>
            <?php if (!$block->isRedirectToCartEnabled()) { ?>
                <script type="text/x-magento-init">
                    {
                "[data-role=tocart-form], .form.map.checkout": {
                    "catalogAddToCart": {}
                }
            }
            </script>
            <?php }; ?>
        <?php }; ?>
    </div>
  </div>
  </div>
<?php }; ?>
<script>
    function add_to_wishlist(i, k) {
        document.getElementById("heart-"+k).removeAttribute("class");
        document.getElementById("heart-"+k).setAttribute("class", "fas fa-heart");
        document.getElementById("add-to-wishlist-btn-"+k).removeAttribute("onclick");
        if(typeof i == 'string') {
            var guest = i;
            var product_id = k;
            var wishlistItems = document.getElementById("wishlist_items_guest").innerText;

            if(!wishlistItems.includes(product_id)) {
                jQuery.ajax({
                    type: "POST",
                    url: "/wishlistAdd.php",
                    data: "guest=" + guest + "&product_id=" + product_id,
                    success: '',
                });

                var current_count = document.getElementById("wish-list-buble").innerText;
                if (current_count >= 0) {
                    var new_count = Number(current_count) + 1;
                    document.getElementById("wish-list-buble").innerText = new_count;
                }
            }
        }
        if(typeof i == 'number') {
            var customer_id = i;
            var product_id = k;
            var wishlistItems = document.getElementById("wishlist_items_user").innerText;
            
            if(!wishlistItems.includes(product_id)) {
                jQuery.ajax({
                    type: "POST",
                    url: "/wishlistAdd.php",
                    data: "customer_id=" + customer_id + "&product_id=" + product_id,
                    success: '',
                });

                var current_count = document.getElementById("wish-list-buble").innerText;
                if (current_count >= 0) {
                    var new_count = Number(current_count) + 1;
                    document.getElementById("wish-list-buble").innerText = new_count;
                }
            }
        }
    }
</script>