<div class="footer-container">
	<div class="container2">
		<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_policies')->toHtml();?>
	</div>
	<div class="footer-info">
		<div class="container">
			<div class="footer-info-container">
				<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_info_type1')->toHtml();?>
			</div>
		</div>
		
	</div>
	<div class="footer">
		<div class="container">
			<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_payment')->toHtml();?>
			<div class="footer-copyright">
				<?php echo $this->getChildHtml("copyright"); ?>
			</div>

		</div>
	</div>
	<div id="back-top"><i class="fa fa-angle-up"></i></div> 
</div>




	