<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Review\Block\Customer\ListCustomer $block */
?>
<?php if ($block->getReviews() && count($block->getReviews())) { ?>
    <div class="table-wrapper reviews">
        <table class="d-md-table table table-bordered table-hover table-responsive table-striped" id="my-reviews-table">
            <caption class="table-caption"><?= $block->escapeHtml(__('Product Reviews')) ?></caption>
            <thead>
                <tr>
                    <th scope="col" class="col date"><?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('created_at')->toHtml(); ?></th>
                    <th scope="col" class="col item"><?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('product_name')->toHtml(); ?></th>
                    <th scope="col" class="col summary"><?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('rating')->toHtml(); ?></th>
                    <th scope="col" class="col description"><?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('product_review')->toHtml(); ?></th>
                    <th scope="col" class="col actions"><?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('action')->toHtml(); ?></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($block->getReviews() as $review) { ?>
                <tr>
                    <td data-th="<?= $block->escapeHtml(__('Created')) ?>" class="col date"><?= $block->escapeHtml($block->dateFormat($review->getReviewCreatedAt())) ?></td>
                    <td data-th="<?= $block->escapeHtml(__('Product Name')) ?>" class="col item">
                        <strong class="product-name">
                            <a href="<?= $block->escapeUrl($block->getProductUrl($review)) ?>"><?= $block->escapeHtml($review->getName()) ?></a>
                        </strong>
                    </td>
                    <td data-th="<?= $block->escapeHtml(__('Rating')) ?>" class="col summary">
                    <?php if ($review->getSum()) { ?>
                        <div class="rating-summary">
                            <span class="label"><span><?= $block->escapeHtml(__('Rating')) ?>:</span></span>
                            <div class="rating-result" title="<?= /* @noEscape */ ((int)$review->getSum() / (int)$review->getCount()) ?>%">
                                <span style="width:<?= /* @noEscape */ ((int)$review->getSum() / (int)$review->getCount()) ?>%;"><span><?= /* @noEscape */ ((int)$review->getSum() / (int)$review->getCount()) ?>%</span></span>
                            </div>
                        </div>
                    <?php } ?>
                    </td>
                    <td data-th="<?= $block->escapeHtmlAttr(__('Review')) ?>" class="col description">
                        <?= $this->helper('Magento\Review\Helper\Data')->getDetailHtml($review->getDetail()) ?>
                    </td>
                    <td data-th="<?= $block->escapeHtmlAttr(__('Actions')) ?>" class="col actions">
                        <a href="<?= $block->escapeUrl($block->getReviewUrl($review)) ?>" class="action more">
                            <span><?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('details')->toHtml(); ?></span>
                        </a>
                    </td>
                </tr>
            <?php } ?>
            </tbody>
        </table>
    </div>
    <?php if ($block->getToolbarHtml()) { ?>
        <div class="toolbar products-reviews-toolbar bottom">
            <?= $block->getToolbarHtml() ?>
        </div>
    <?php } ?>
<?php } else { ?>
    <div class="message info empty"><span><?= $block->escapeHtml(__('You have submitted no reviews.')) ?></span></div>
<?php } ?>
<div class="actions-toolbar">
    <div class="secondary">
        <a class="action back" href="<?= $block->escapeUrl($block->getBackUrl()) ?>">
            <span><?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('go_back')->toHtml(); ?></span>
        </a>
    </div>
</div>