<?php 
use Magento\Framework\App\Action\Action;

if($this->getConfig('enabled')) { ?>
	<?php
	$speed = $block->getConfig('speed') ? $block->getConfig('speed'):1500;
	$show_navigation =$block->getConfig('next_back');
	$navigation=false;
	if($show_navigation==1) {
		$navigation=true;
	}
	$show_pagination = $block->getConfig('nav_ctrl');
	$auto = $block->getConfig('auto');
	?>
	<?php $_productCollection = $this->getProducts();
	$_helper = $this->helper('Magento\Catalog\Helper\Output');
	$tvHelper = $this->helper('Themevast\Themevast\Helper\Data');
	$show_shortdescription = $block->getConfig('description')==1 ? true:false;
	$length = $block->getConfig('maxlength') ? $block->getConfig('maxlength'):50;
	?>
	<div class="bestsellerproduct list-products">		
		<?php			
			if ($block->getMode() == 'grid') {
				$viewMode = 'grid';
				$image = 'category_page_grid';
				$showDescription = false;
				$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
			} else {
				$viewMode = 'list';
				$image = 'category_page_list';
				$showDescription = true;
				$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
			}
			$pos = $block->getPositioned();			
		?>
		<?php if($this->getConfig('title')){  ?>
			<div class="title-product-heading title-bestseller-heading">
				<h2>
					<?php echo $this->getConfig('title')?>
				</h2>
			</div>
		<?php }?>
		<?php if(!$_productCollection->getSize()) { ?> 
			<div class="message info empty">	
				<p class="note-msg">
					<?php echo __('There are no products matching the selection.') ?>
				</p>
			</div>
		<?php } else { ?>
			<?php
			$rows = $this->getConfig('row_show');
			?>	
			<div class="owl-carousel">
				<?php $_collectionSize = $_productCollection->count() ?>
				<?php $i=0; foreach ($_productCollection as $_product) { ?>
					<?php if($i %$rows == 0) echo "<div class='item bestsellerproduct-item'>"; ?>
						<div class="product-item clearfix">					
							<?php
							$productImage = $block->getImage($_product, $image);
							if ($pos != null) {
								$position = ' style="left:' . $productImage->getWidth() . 'px;'
									. 'top:' . $productImage->getHeight() . 'px;"';
							}
							?>							
							<div class="product-photo">
								<?php // Product Image ?>
								<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
									<?php $productImageThumb = $block->getImage($_product, 'category_page_grid-1');?>
									<span class="image0 image-switch">
										<?php echo $productImage->toHtml(); ?>
									</span>
									<span class="image1 image-switch">
										<?php echo $productImageThumb->toHtml(); ?>
									</span>
								</a>
							</div>
							<div class="product-info">
								<?php
									$_productNameStripped = $block->stripTags($_product->getName(), null, true);
								?>
								<h3 class="product-name">
									<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
										<?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
									</a>
								</h3>
								<?php if ($show_shortdescription) { ?>
									<?php $shortDescription = $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description'); ?>
									<?php if ($shortDescription) { ?>
										<div class="des">
											<?php echo $tvHelper->changeString($shortDescription,$length,' ...'); ?>
										</div>
									<?php } ?>
								<?php } ?>
								<?php if($this->getConfig('review')) { ?>
									<?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
								<?php } ?>
								<?php if($this->getConfig('show_price')) { ?>
									<?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
								<?php } ?>
							
							</div>
						<?php $i++;?>
					</div>
					<?php if($i %$rows == 0) echo "</div>"; ?>                  
				<?php } ?>
					<?php if($i %$rows != 0) echo "</div>"; ?>                
			</div>
		<?php if (!$block->isRedirectToCartEnabled()) { ?>
			<script type="text/x-magento-init">
			{
				"[data-role=tocart-form], .form.map.checkout": {
					"catalogAddToCart": {}
				}
			}
			</script>
		<?php } ?>
			<script>
				require([
					'jquery',
					'mage/mage',
					'themevast/owl'
				], function ($) {
					'use strict';

					jQuery(".bestsellerproduct .owl-carousel").owlCarousel({
						autoplay :<?php echo $auto==1 ? 'true':'false' ?>,
						items : 1,
						smartSpeed : <?php echo $speed ?>,
						dotsSpeed : <?php echo $speed ?>,
						rewindSpeed : <?php echo $speed ?>,
						nav : <?php echo $show_navigation==1 ? 'true' : 'false';?>,
						autoplayHoverPause : true,
						dots :<?php echo $show_pagination==1 ? 'true':'false' ;  ?>,
						scrollPerPage:true,
						margin:0,
						responsive: {
						0: {
							items: 1,
						},
						480: {
							items:1,
						},
						768: {
							items:1,
						},
						991: {
							items:1,
						},						
						1200: {
							items:1,
						}
					 }
					});
				});
			</script>
	<?php } ?>
	</div>
<?php } ?>