<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<?php
/** @var $block \Magento\Framework\View\Element\Template */
/** @var $helper \Magento\Search\Helper\Data */
$helper = $this->helper('Magento\Search\Helper\Data');
?>
<div class="block-search">
    <div class="block-content">
        <form class="form minisearch" id="search_mini_form" action="<?php /* @escapeNotVerified */ echo $helper->getResultUrl() ?>" method="get">
            <div class="field search">
                <div class="control">
                  <div class="seclect-cat">
                    <select name="cat" id="choose_category">
                      <option value=""><?php echo __('All Categories'); ?></option>
                    <?php $categories = $block->getCategories(); 
                    foreach($categories as $cat)
                    {
                      ?>
                      <option value="<?php echo $cat->getId(); ?>"><?php echo $cat->getName(); ?></option>
                      <?php
                    }
                    ?>
                    </select>
                  </div>
                  <div class="auto-search">
                    <input id="search"
                           data-mage-init='{"quickSearch":{
                                "formSelector":"#search_mini_form",
                                "url":"<?php /* @escapeNotVerified */ echo $block->getUrl('search/ajax/suggest', ['_secure' => $block->getRequest()->isSecure()]); ?>",
                                "destinationSelector":"#search_autocomplete"}
                           }'
                           type="text"
                           name="<?php /* @escapeNotVerified */ echo $helper->getQueryParamName() ?>"
                           value="<?php /* @escapeNotVerified */ echo $helper->getEscapedQueryText() ?>"
                           placeholder="<?php /* @escapeNotVerified */ echo __('Search for products'); ?>"
                           class="input-text"
                           maxlength="<?php /* @escapeNotVerified */ echo $helper->getMaxQueryLength();?>"
                           role="combobox"
                           aria-haspopup="false"
                           aria-autocomplete="both"
                           autocomplete="off"/>
                      <div id="search_autocomplete" class="search-autocomplete"></div>
                      <?php echo $block->getChildHtml() ?>
                    </div>
                </div>
            </div>
            <div class="actions">
                <button type="submit"
                        title="<?php echo $block->escapeHtml(__('Search')) ?>"
                        class="btn-search">
                    <i class="storm-zoom"></i>
                </button>
            </div>
        </form>
        
    </div>
</div>

<script type="text/javascript">
    require([
        'jquery',
        'themevast/choose'
    ], function ($) {
		$("#choose_category").chosen();
    });
</script>