<div class="footer-info-container">
	<div class="footer-info">
		<div class="footer-column footer-column-1 col-md-12 col-sm-12">
			<p class="footer-logo">

			</p>
			<ul>
				<li class="social-facebook"><a href="#" title="Facebook"><i class="fa fa-facebook"></i></a></li>
				<li class="social-twitter"><a href="#" title="Twitter"><i class="fa fa-twitter"></i></a></li>
				<li class="social-google"><a href="#" title="Google"><i class="fa fa-google-plus"></i></a></li>
				<li class="social-email"><a href="#" title="Email"><i class="fa fa-envelope"></i></a></li>
				<li class="social-pinterest"><a href="#" title="Pinterest"><i class="fa fa-pinterest"></i></a></li>
			</ul>
		</div>
		<div class="clearfix visible-lg-block"></div>
		<div class="footer-column footer-column-2 col-md-2 col-sm-6">
			<div class="footer-widget">
				<h5 class="widget-title">Our Stores</h5>			
				<div class="textwidget">
					<ul class="menu">
						<li><a href="#">New York</a></li>
						<li><a href="#">London SF</a></li>
						<li><a href="#">Cockfosters BP</a></li>
						<li><a href="#">Los Angeles</a></li>
						<li><a href="#">Chicago</a></li>
						<li><a href="#">Las Vegas</a></li>
					</ul>
				</div>
			</div>						
		</div>
		<div class="footer-column footer-column-3 col-md-2 col-sm-6">
			<div class="footer-widget">
				<h5 class="widget-title">INFORMATION</h5>			
				<div class="textwidget">
					<ul class="menu">
						<li><a href="#">About Store</a></li>
						<li><a href="#">New Collection</a></li>
						<li><a href="#">Woman Dress</a></li>
						<li><a href="#">Contact Us</a></li>
						<li><a href="#">Latest News</a></li>
						<li><a href="#">Our Sitemap</a></li>
					</ul>
				</div>
			</div>						
		</div>
		<div class="footer-column footer-column-4 col-md-2 col-sm-6">
			<div class="footer-widget">
				<h5 class="widget-title">USEFUL LINKS</h5>			
				<div class="textwidget">
					<ul class="menu">
						<li><a href="#">Privacy Policy</a></li>
						<li><a href="#">Returns</a></li>
						<li><a href="#">Terms & Conditions</a></li>
						<li><a href="#">Contact Us</a></li>
						<li><a href="#">Latest News</a></li>
						<li><a href="#">Our Sitemap</a></li>
					</ul>
				</div>
			</div>						
		</div>
		<div class="footer-column footer-column-5 col-md-2 col-sm-6">
			<div class="footer-widget">
				<h5 class="widget-title">FOOTER MENU</h5>			
				<div class="textwidget">
					<ul class="menu">
						<li><a href="#">Instagram profile</a></li>
						<li><a href="#">New Collection</a></li>
						<li><a href="#">Woman Dress</a></li>
						<li><a href="#">Contact Us</a></li>
						<li><a href="#">Latest News</a></li>
						<li class="purchase"><a href="#">Purchase Theme</a></li>
					</ul>
				</div>
			</div>						
		</div>
		<div class="footer-column footer-column-6 col-md-4 col-sm-12">
			<div class="footer-widget">
				<h5 class="widget-title">About The Store</h5>
				<div class="textwidget">
					<p>STORE - worldwide fashion store since 1978. We sell over 1000+ branded products on our web-site.</p>
					<div>
						<i class="fa fa-location-arrow"></i> 451 Wall Street, USA, New York<br>
						<i class="fa fa-mobile"></i> Phone: (064) 332-1233<br>
					</div>
					<br>
					<p><img src="//xtemos3.r.worldssl.net/basel/wp-content/uploads/2015/08/payments.png"></p>
				</div>
			</div>
		</div>
	</div>

</div>