<?php

/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 *
 * @var $block \Magento\Customer\Block\Account\Forgotpassword
 */

// @codingStandardsIgnoreFile

?>
<form class="my-5" action="<?php /* @escapeNotVerified */ echo $block->getUrl('*/*/forgotpasswordpost') ?>" method="post" id="form-validate" data-mage-init='{"validation":{}}'>
    <div data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
        <div>
            <?php /* @escapeNotVerified */ echo __('Please enter your email address below to receive a password reset link.'); ?></div>
        <div class="my-3">
            <input placeholder="Email" type="email" name="email" alt="email" id="email_address" class="rounded form-control shadow-none" value="<?php echo $block->escapeHtml($block->getEmailValue()) ?>" data-validate="{required:true, 'validate-email':true}">
        </div>
        <?php echo $block->getChildHtml('form_additional_info'); ?>
    </div>
    <div class="row align-items-center">
        <div class="col-6 col-sm-3 col-lg-2">
            <button type="submit" class="btn btn-java btn-block"><span><?php /* @escapeNotVerified */ echo __('Submit') ?></span></button>
        </div>
        <div class="col-6 col-sm-9 col-lg-10 text-right">
            <a class="text-body" href="<?php /* @escapeNotVerified */ echo $block->getLoginUrl() ?>"><span><?php /* @escapeNotVerified */ echo __('Go back') ?></span></a>
        </div>
    </div>
</form>