<?php
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_Marketplace
 * @version     1.2
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2017 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 *
 */

$sellerGroupId = $customerId = $customerGroupId = $status = '';
$urlInterface = \Magento\Framework\App\ObjectManager::getInstance()->get('Magento\Framework\UrlInterface');
$currentUrl = $urlInterface->getCurrentUrl();
$helper = $this->helper('Apptha\Marketplace\Helper\Objectmanager');
$customerSession = $helper->customerSession();
$customerDatas = $customerSession->getCustomer();
if ($customerSession->isLoggedIn()) {
    $customerId = $customerSession->getId();
    $customerGroupId = $customerDatas->getGroupId();
    $helper = $this->helper('Apptha\Marketplace\Helper\Objectmanager');
    $sellerGroupData = $helper->customerSessionGroup($customerGroupId);
    $sellerGroupId = $sellerGroupData->getId();
    $status = $helper->sellerStatus($customerId);
}
$reviewSellerId = $this->getRequest()->getParam('seller_id');
$helper = $this->helper('Apptha\Marketplace\Helper\Objectmanager');
$requestInterface = $helper->actionController();
$routeName = $requestInterface->getRouteName();
$action = $requestInterface->getActionName();
if ($routeName != 'catalog' && $routeName != 'catalogsearch' && ($customerGroupId==$sellerGroupId && $status==1)) {
?>
<div class="block account-nav" <?php if($routeName !='marketplace' && $routeName !='vacationmode' && $action !='view') { ?>style="margin-bottom:-25px;<?php } ?>"
    <?php if(!empty($reviewSellerId)) { echo 'style="display:none;"'; } ?>>
    <div class="title account-nav-title">
        <?php
        if($customerId == 10 || $customerId == 11) { ?>
            <strong>Master's Account</strong>
        <?php
        }
        ?>
    </div>
    <div class="content">
        <nav class="account-nav">
            <ul class="nav items">
            <?php
            $seller = $this->helper( 'Apptha\Marketplace\Helper\Data' );
            $assignProduct = $seller->getAssignProduct ();
            $isSellerReviewEnabled = $seller->isSellerReviewEnabled (); ?>
                <!-- MASTER -->
                <?php if ($customerId == 10 || $customerId == 11) { ?>           
                    <li class="nav item <?php if($currentUrl==$block->getUrl('customer/account/')) { ?>current<?php } ?>">
                        <a href="<?php echo $block->getUrl('customer/account/') ?>"><?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('account_settings')->toHtml();?></a>
                    </li>
                    <li class="nav item <?php if($currentUrl==$block->getUrl('marketplace/seller/dashboard')) { ?>current<?php } ?>">
                        <a href="<?php echo $block->getUrl('marketplace/seller/dashboard') ?>">Marketplace Settings</a>
                    </li>                    
                    <li class="nav item <?php if($currentUrl==$block->getUrl('marketplace/order/manage')) { ?>current<?php } ?>">
                        <a href="<?php echo $block->getUrl('marketplace/order/manage') ?>">View Transports</a>
                    </li>
                    <li class="nav item <?php if($currentUrl==$block->getUrl('marketplace/product/manage') || $currentUrl==$block->getUrl('marketplace/product/add')) { ?>current<?php } ?>">
                        <a href="<?php echo $block->getUrl('marketplace/product/manage') ?>">Manage Invoices</a>
                    </li>
                    <li class="nav item">
                        <a href="<?php echo $block->getUrl('marketplace/seller/profile/') ?>">Store Info</a>
                    </li>
                <?php } ?>
                <?php
                $adminApproval = $seller->getContactAdmin ();
                if ($adminApproval) { ?>
                    <li class="nav item <?php if($currentUrl==$block->getUrl('marketplace/contact/form')) { ?>current<?php } ?>">
                        <a href="<?php echo $block->getUrl('marketplace/contact/form') ?>"><?php echo __('Contact Admin'); ?></a>
                    </li>
                <?php } ?>
                <?php
                $isSellerSubscriptionEnabled = $seller->isSellerSubscriptionEnabled ();
                if ($isSellerSubscriptionEnabled) { ?>
                    <li class="nav item <?php if($currentUrl==$block->getUrl('marketplace/seller/subscriptionplans')) { ?>current<?php } ?>">
                        <a href="<?php echo $block->getUrl('marketplace/seller/subscriptionplans') ?>"><?php echo __('Subscription Plans'); ?></a>
                    </li>
                <?php } ?>
            </ul>
        </nav>
    </div>
</div>
<?php 
}
?>